### ISSUE TITLE
New collection types break the layout for HYPER MOULINETTE and COLLECTION HIGHLIGHTER

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#103]
For both HYPER MOULINETTE and COLLECTION HIGHLIGHTER.
We can have multiple types of collections.

**Comment by jesus2099** [comment]
I hadn’t notice that there now were other type of collections and that when you had some event collections, the **COLLECTION HIGHLIGHTER** would not show in front of the normal release collections. 
It was quick fixed by @bricas through his PR #102.
Now both **HYPER MOULINETTE** and **COLLECTION HIGHLIGHTER** need some better GUI as they were made in the time when there only were **release** collections and they shouldn’t be run against any of the other types.

**Comment by bricas** [comment]
If you want it to only do release collections, could you not change line 128/129 to:

		/*collection loader*/
		var xp1 = document.evaluate("//xhtml:table[contains(@class, 'tbl')]/xhtml:thead//xhtml:th[contains(./text(), 'Releases')]", document, nsr, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);

Note the `xhtml:th[contains(./text(), 'Releases')]` instead of searching for "Collection."

**Comment by jesus2099** [comment]
It will not work in [localised versions of MBS](https://beta.musicbrainz.org) although I don’t know when it will go live anyway (and I can also test all current languages against).
And at the same time, there is no other means, at first sight. :)

**Comment by bricas** [comment]
If we could get MB to add a class to each table that would identify them by type, then this problem would be solved much more simply :)

**Comment by jesus2099** [comment]
I was already said to be too invasive in their JIRA so I prefer limiting my requests over there for the important things (that cannot be work‐arounded). ;)
There are so many open tickets…
