### ISSUE TITLE
mb. ELEPHANT EDITOR script no longer works for me

### ISSUE THREAD

**Issue by AzoresOne** [jesus2099/konami-command#105]
mb. ELEPHANT EDITOR script no longer works for me.
There are no errors, it simply doesn't show up. Tried uninstalling and re-installing.
Tried disabling all other scripts installed. All I can add is that I remember Greasemonkey
updating some script (I don't recall which one, maybe the one in question, maybe mb. SUPER MIND CONTROL II X TURBO) and it ceased to appear in MBz edits.
[Apps]
mb. ELEPHANT EDITOR
Version: 2015.6.14.1302
Mozzila Firefox
Version: 40.0.2
[Extra Info]
Mangage User Scripts... Greasemonkey User Script Preferences - mb. ELEPHANT EDITOR
User Settings tab, under Included Pages:
http"://*musicbrainz.org/*

Script Settings tab, under Included Pages:
http*://*musicbrainz.org/*/add-alias
http*://*musicbrainz.org/*/change-quality
http*://*musicbrainz.org/*/create*
http*://*musicbrainz.org/*/delete
http*://*musicbrainz.org/*/edit
http*://*musicbrainz.org/*/edit_annotation
http*://*musicbrainz.org/*/merge
http*://*musicbrainz.org/*/merge?*
http*://*musicbrainz.org/Vmove?dest=*
http*://*musicbrainz.org/*/remove*
http*://*musicbrainz.org/*edits*
http*://*musicbrainz.org/attist/*/split
http*://*musicbrainz.org/cdtoc/*
http*://*musicbrainz.org/edit/*
http*://*musicbrainz.org/edit/artist/add.html?"
http*://*musicbrainz.org/edit/subscribed*
http"://*musicbrainz.org/isrc/delete*
http*://*musicbrainz.org/mod/*
http*://*musicbrainz.org/recording/*/add-isrc
http*://*musicbrainz.org/release*/*/*-cover-art*
http*://*musicbrainz.org/release/*/ed it-relationships
http*://*musicbrainz.org/release/add*
http*://*musicbrainz.org/work/*/add-iswc
http*://acoustid.org/edit/*

Greasemonkey options: all boxes checked

**Comment by jesus2099** [comment]
Hi, thanks for the ticket. :)
Do you remember around when it ceased functioning ?

**Comment by AzoresOne** [comment]
I dunno really, maybe a week ago...

**Comment by AzoresOne** [comment]
Is is not working (in Firefox) for you as well? I hope you don't give up on Firefox, this is a very handy script.

**Comment by jesus2099** [comment]
No no I don’t give up any of those browser support (Opera classic, Firefox Chromium).
I just don’t test Firefox and Chromium that often.
Update your script, it should work now, tell me. :)

**Comment by AzoresOne** [comment]
Back up and running smooth again :)
I'm a lazy typer and I hate re-typing things over and over, so this script is awesome!

**Comment by jesus2099** [comment]
Hehe, so we are alike, then. :)
Make sure you have installed a 2015 version. I made a mistake, a 2018 (that blocks auto-updates) version was temporarily online.
Tristan.
