### ISSUE TITLE
Undefined variable: do108889

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#131]
When loading error : 

> Event thread: click
> Uncaught exception: ReferenceError: Undefined variable: **do108889**
> Error thrown at line 380, column 14 in <anonymous function>(event):
> 	err.parentNode.removeChild(err);

**Comment by jesus2099** [comment]
It is fixed but will be merged to master branch (live for users) only when #61 is fixed.

**Comment by jesus2099** [comment]
I reopen because it is not fixed in the public version.

**Comment by zapartowy** [comment]
https://github.com/jesus2099/konami-command/labels/mb_ALL-LINKS
