### ISSUE TITLE
Add a “release date” column on label relationships pages

### ISSUE THREAD

**Issue by Lotheric** [jesus2099/konami-command#132]
It would be useful for a label like this one :
http://musicbrainz.org/label/0b805b9c-ea03-4fc1-b50d-6dcef76433e0/relationships

**Comment by jesus2099** [comment]
You don't want this in super turbo?

**Comment by Lotheric** [comment]
I already use super turbo so I don't mind at all :)

**Comment by jesus2099** [comment]
I called the column **Release events** as I display countries and there are several of them on many releases.
