### ISSUE TITLE
Advanced rate limiter

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#142]
I must try to understand this @kepstin [advanced rate limiter](//gist.github.com/kepstin/2364412).
He has left some useful explanations in [IRC logs](http://chatlogs.metabrainz.org/brainzbot/metabrainz/msg/3463387/).

My rate limiter queues the requests and launch them at a rate of **maximum 1 per second**.

> new request start time − previous request start time ≥ 1 second

His rate limiter would launch 10 simultaneous requests then make sure there is never more than 10 requests launched in 10 seconds, for the remaining queued requests.

It would make it very faster than mine for batches of 10 or less.

I have to find out the actual MB guidelines about rate limiting as kepstin says it would be **max 10 requests within 10 seconds** but [Rate limiting](http://wiki.musicbrainz.org/XML_Web_Service/Rate_Limiting#Source_IP_address) says **max 1 request per second** (per IP) and I think I have read something like **max 22(?) requests within 43(?) seconds** in the 503 error slow down pages…

**Comment by jesus2099** [comment]
In the [*Slow Down* page](//github.com/metabrainz/musicbrainz-server/blob/6e2ee85825e5cbea99d03ffda6e31d3f9c9d142f/lib/MusicBrainz/Server/RateLimitResponse.pm#L17-L20), we have this info : 

> « *limit is `{limit}` per `{period}` seconds* » 

Where `{limit}` is the accepted amount of requests within `{period}` seconds.

I can’t make a dynamic rate limiter ; I didn’t find in the code where those values are set, I see they are read from *socket data*.
It’s only at run time that I could get up to date values (little bit too late). If a user script goes beyond limits, it could read the [`X-Rate-Limited` header](//github.com/metabrainz/musicbrainz-server/blob/6e2ee85825e5cbea99d03ffda6e31d3f9c9d142f/lib/MusicBrainz/Server/Controller/Root.pm#L306) or parse that *Slow Down* page…

The [spirit](http://chatlogs.metabrainz.org/brainzbot/musicbrainz/msg/3464239/) is still [max 1 request per second](http://wiki.musicbrainz.org/XML_Web_Service/Rate_Limiting) but it seems [accepted](http://chatlogs.metabrainz.org/brainzbot/metabrainz/msg/3464269/) to proceed with @kepstin’s **max 10 requests within 11 seconds**.

**Comment by jesus2099** [comment]
Being able to launch around 10 initial requests (I would queue an empty slot first  — for the already loaded current page — then 9 actual requests) could greatly improve **MERGE HELPOR 2** and **PENDING EDITS** (associated artists).
It would not really enhance **COLLECTION HIGHLIGHTER** nor HYPER MOULINETTE, maybe it would even be hard to make them work with that engine (because IIRC each request requires the previous response).

**Comment by kepstin** [comment]
One thing to keep in mind is that you need to maintain a long-term average of 1 request/second even over multiple page loads or refreshes. E.g. what happens if someone opens a bunch of tabs where your script is running in all of them?

Unless you can coordinate the rate limit over multiple tabs and multiple page loads, I recommend using a simple 1 req/second method.

**Comment by jesus2099** [comment]
Thanks @kepstin, indeed !
So there’s only **MERGE HELPOR 2** left, then — as we can’t open several different merge pages.

**Comment by jesus2099** [comment]
A solution to coordinate between multiple pages would be to store the queue in `localStorage` but that would be too much work for little gain.
When we open multiple tabs, we are not expecting all tabs to load fast, we don’t even go to all tabs fastly.

**Comment by jesus2099** [comment]
It may fix #115.

**Comment by jesus2099** [comment]
I close this now that #115 is fixed.
But this advanced rate limiter is so clever I wish I would use it in the future! :)
