### ISSUE TITLE
mb ALL LINKS: http://musicbrainz.org/static/images/favicons/discogs-16.png doesn't exist

### ISSUE THREAD

**Issue by zas** [jesus2099/konami-command#154]
While checking our server-side logs i noticed queries for this icon, that doesn't exist.
I tracked it down to https://github.com/jesus2099/konami-command/blob/master/mb_ALL-LINKS.user.js#L88

**Comment by reosarevok** [comment]
http://musicbrainz.org/static/images/favicons/discogs-32.png does exist, for what it's worth, so you could use that if size won't mess up things I guess?

**Comment by jesus2099** [comment]
Oh Thank you very much !
I didn’t notice the removal in metabrainz/musicbrainz-server@2acd4a18ca1231c7218ad2d43f2b2a1ba34c000e
Actually it seems that many favicons are not displaying in my auto links, I’ll check several of them.
Is it the only one that is flooding your logs, @zas ?

**Comment by jesus2099** [comment]
I have to start and finish #61 as fast as possible before removing that line, except if it is important that I do it very soon, @zas.

**Comment by jesus2099** [comment]
Above commit ↑↑↑ is not on master branch (not released) until #61 is done.
