### ISSUE TITLE
MBS new February 2016 design

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#156]
[BETA.musicbrainz.org](http://beta.musicbrainz.org)

All the TURBO menu items have disappeared from Editing menu : settings, release clone, batch recording-work AR item.
Same thing for local storage manager’s menu item in About menu.

- [x] mb_COLLECTION-HIGHLIGHTER
- [x] mb_LOCAL-STORAGE-MANAGER
- [x] mb_PENDING-EDITS
- [x] mb_SUPER-MIND-CONTROL-II-X-TURBO

**Comment by jesus2099** [comment]
The left border has disappeared from search page http://beta.musicbrainz.org/search?type=artist&query=ajico

**Comment by jesus2099** [comment]
User menu merger and static menu bar too.

**Comment by jesus2099** [comment]
I don’t see mb_PENDING-EDITS any more

**Comment by vzell** [comment]
I have version 2016.2.9 of mb. SUPER MIND CONTROL Ⅱ X TURBO under firefox 44.0.2 and nothing of the functionality is working anymore. Running 2016.1.26 works fine

**Comment by jesus2099** [comment]
Hello @vzell, I think you may be using main [MusicBrainz.org](http://musicbrainz.org) server, aren’t you?
In this case, you have a problem because of #155.

I changed TURBO script recently to fix some [beta](http://beta.musicbrainz.org) changes (#155) but now new changes are required because beta has changed again (this ticket #156).

My script are currently unstable because I am now using beta and beta is unstable by definition.

I hope I will be using main server again soon, the pace of changes is less hectic and easier to follow. :)

Sorry for the time being.

**Comment by jesus2099** [comment]
Cool links are gone too.

**Comment by jesus2099** [comment]
There a few exceptions but I have to officially announce 1 week without user script on either main and beta servers. ;)

**Comment by vzell** [comment]
Thanks for letting me know...

**Comment by jesus2099** [comment]
*standout* seems to still be NG in REVIVE-EDITORS.
And TAG_TOOLS seem broken as well

**Comment by jesus2099** [comment]
My two columns missing in work page.
 —  —  — 
OK I think I must stop using beta…
I’m waiting for next release that will contain new design on main server and start repairing again only then.

**Comment by bricas** [comment]
IMHO, i would expect the master branch to work against the live site. Perhaps you could have a "beta" branch with changes that you test against beta. You could always merge them up to master when they go live. Or just ignore beta entirely and stick with live :)

**Comment by jesus2099** [comment]
You’re absolutely right, @bricas. :) 
I regret my move.
I really had to work on beta because of really bad performance on main. I was so fed up and I recently realised that beta is running 3 times faster than main.
I hadn’t noticed #155 problem was only on beta then I never thought changes were so frequent on beta, which is in fact ever changing (and it’s in fact natural).

I now wait for the 2 big changes (relative paths and design change, tomorrow or next Tuesday) to go main before fixing my scripts.
I’ll probably go back supporting only main and use beta for my editing only when it works… :/

I hope one day, something can be done to make main faster ([MBS-8799](http://tickets.musicbrainz.org/browse/MBS-8799)).

**Comment by jesus2099** [comment]
Scripts should run again on main site.
I have moved #155’s changes to a `beta` branch instead, thanks to @bricas advice. :+1:

**Comment by bricas** [comment]
So yeah, the latest re-branding broke the highlighter. Although I don't really know, my cursory debugging has led me to this line: https://github.com/jesus2099/konami-command/blob/master/mb_COLLECTION-HIGHLIGHTER.user.js#L244

On pages like "collection" and "release-group" the list of links does not include the server address and it looks like we're only looking for non-server prepended links on "release" pages.

So changing
```
cat == "release" ?
```

to
```
cat == "release" || cat == "collection" || cat == "release-group" ?
```
Works, but seems horribly incomplete.

**Comment by bricas** [comment]
Add cat == "series" to that... :)

**Comment by jesus2099** [comment]
Thanks @bricas, here is how I had fixed it in beta branch: ba1b4406232bcc568ec24192682022fb972302ed.
I have merged beta to master branch and am adjusting other stuff at the same time.
I will push changes soon now, when I have some free time. :)
I will check if series work too by the way, I have not done that yet, thank you.

**Comment by jesus2099** [comment]
It’s now roughly fixed.
I close the ticket and stuff that remains broken will get new tickets.

**Comment by jesus2099** [comment]
Server code released on [2016-02-22](http://blog.musicbrainz.org/?p=3775) as [v-2016-02-22](https://github.com/metabrainz/musicbrainz-server/releases/tag/v-2016-02-22).
