### ISSUE TITLE
mb_FUNKEY-ILLUSTRATED-RECORDS: OpenUserJS metadata block needed

### ISSUE THREAD

**Issue by Martii** [jesus2099/konami-command#158]
Since you have [multi-line Function Expression strings](https://github.com/jesus2099/konami-command/blob/8785f7f65498dec43dea2eb43a02bf5874c9d74a/mb_FUNKEY-ILLUSTRATED-RECORDS.user.js#L2-L3) in this script... you may want to put this [around here](https://github.com/jesus2099/konami-command/blob/8785f7f65498dec43dea2eb43a02bf5874c9d74a/mb_FUNKEY-ILLUSTRATED-RECORDS.user.js#L58-L60).

Your metadata block parser probably isn't aware of this metadata block so outside the UserScript Metadata Block might be preferable at this time.

The syntax is as follows:

``` js
// ==OpenUserJS==
// @unstableMinify Multi-line string comments using Function Expressions
// ==/OpenUserJS==
```

... please note you must give a reason after this key otherwise it won't notify your users. Feel free to change the reason why you suggest minification may be unusable in your scripts.

Any script that utilizes multi-line Function Expression strings needs this metadata block.

TIA

OUJS Admin

**Comment by jesus2099** [comment]
I guess I should do this to all my scripts that have a metadata block parser. :)

**Comment by jesus2099** [comment]
Thanks @Martii for the tip.

**Comment by Martii** [comment]
No problem. Thank you. Hopefully I'll have some time to get this fixed at a later date with the dependency we use... it's an old bug on their project. Still want to give them every opportunity though. :)

**Comment by Martii** [comment]
One other quickie too... I've been contemplating doing an example of [template strings](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Template_literals#Multi-line_strings) with parsers. There is [a basic Unit Test here](https://openuserjs.org/scripts/Marti/RFC_2606%C2%A73_-_ES6_Template_String_Unit_Test) but haven't made one for parsing yet... is limited to ES6+ capable browsers/.user.js engines though.

**Comment by jesus2099** [comment]
Is the bug _only_ mishoo/UglifyJS2#88 or are there others ?

**Comment by Martii** [comment]
There are some issue currently with ES6 arrow functions since we are using their experimental [harmony support](https://github.com/mishoo/UglifyJS2/issues/448) branch. I am planning on reporting them at *UglifyJS2* approximately once a month. *(need to figure out reduced test cases too)* Most ES5 is pretty solid I believe. I update our fork of that project about once a week if needed... so things could change. This is why it's a "suggestion that minification" may not be usable. Cc: @fabiosantoscode

**Comment by fabiosantoscode** [comment]
I would defenitely like to see those issues. I've been on a little bit of a hiatus when it comes to working on UglifyJS, but I've been doing some stuff lately (namely a local branch with ES6 imports)

**Comment by Martii** [comment]
@jesus2099 

Thought of something just now *(better late than never)* that would let you and your users test/use .min.user.js versions but should have minimal code impact... try it first though as it's untested with the metadata block parser. Currently seems to work in *UglifyJS2*:

``` js
var meta = {rawmdb: function() {
// ==UserScript==
// @name         mb. FUNKEY ILLUSTRATED RECORDS
// @version      2016.6.15
// @changelog    https://github.com/jesus2099/konami-command/commits/master/mb_FUNKEY-ILLUSTRATED-RECORDS.user.js
// @description  musicbrainz.org: CAA front cover art archive pictures/images (release groups and releases) Big illustrated discography and/or inline everywhere possible without cluttering the pages
// @homepage     http://userscripts-mirror.org/scripts/show/154481
// @supportURL   https://github.com/jesus2099/konami-command/labels/mb_FUNKEY-ILLUSTRATED-RECORDS
// @compatible   opera(12.18.1872)+violentmonkey  my setup
// @compatible   firefox(39)+greasemonkey    quickly tested
// @compatible   chromium(46)+tampermonkey   quickly tested
// @compatible   chrome+tampermonkey         should be same as chromium
// @namespace    https://github.com/jesus2099/konami-command
// @downloadURL  https://github.com/jesus2099/konami-command/raw/master/mb_FUNKEY-ILLUSTRATED-RECORDS.user.js
// @updateURL    https://github.com/jesus2099/konami-command/raw/master/mb_FUNKEY-ILLUSTRATED-RECORDS.user.js
// @author       PATATE12
// @licence      CC BY-NC-SA 3.0 (https://creativecommons.org/licenses/by-nc-sa/3.0/)
// @since        2012-12-19
// @icon         data:image/gif;base64,R0lGODlhEAAQAKEDAP+/3/9/vwAAAP///yH/C05FVFNDQVBFMi4wAwEAAAAh/glqZXN1czIwOTkAIfkEAQACAwAsAAAAABAAEAAAAkCcL5nHlgFiWE3AiMFkNnvBed42CCJgmlsnplhyonIEZ8ElQY8U66X+oZF2ogkIYcFpKI6b4uls3pyKqfGJzRYAACH5BAEIAAMALAgABQAFAAMAAAIFhI8ioAUAIfkEAQgAAwAsCAAGAAUAAgAAAgSEDHgFADs=
// @require      https://greasyfork.org/scripts/10888-super/code/SUPER.js?version=70394&v=2015.8.27
// @grant        none
// @match        *://*.mbsandbox.org/
// @match        *://*.mbsandbox.org/artist/*
// @match        *://*.mbsandbox.org/cdtoc/*
// @match        *://*.mbsandbox.org/collection/*
// @match        *://*.mbsandbox.org/label/*
// @match        *://*.mbsandbox.org/recording/*
// @match        *://*.mbsandbox.org/release/*
// @match        *://*.mbsandbox.org/release-group/*
// @match        *://*.mbsandbox.org/search?*type=annotation*
// @match        *://*.mbsandbox.org/search?*type=release*
// @match        *://*.mbsandbox.org/series/*
// @match        *://*.mbsandbox.org/tag/*
// @match        *://*.mbsandbox.org/user/*/ratings*
// @match        *://*.mbsandbox.org/user/*/tag/*
// @match        *://*.musicbrainz.org/
// @match        *://*.musicbrainz.org/artist/*
// @match        *://*.musicbrainz.org/cdtoc/*
// @match        *://*.musicbrainz.org/collection/*
// @match        *://*.musicbrainz.org/label/*
// @match        *://*.musicbrainz.org/recording/*
// @match        *://*.musicbrainz.org/release/*
// @match        *://*.musicbrainz.org/release-group/*
// @match        *://*.musicbrainz.org/search?*type=annotation*
// @match        *://*.musicbrainz.org/search?*type=release*
// @match        *://*.musicbrainz.org/series/*
// @match        *://*.musicbrainz.org/tag/*
// @match        *://*.musicbrainz.org/user/*/ratings*
// @match        *://*.musicbrainz.org/user/*/tag/*
// @exclude      *.org/cdtoc/remove*
// @exclude      *.org/release/*/*edit*
// @exclude      *.org/series/*/*edit*
// @run-at       document-end
// ==/UserScript==
'';
}};
```

... similar to `"use strict";`. :smile_cat:

**Comment by jesus2099** [comment]
Thanks @Martii, I’ll look into this. :)
