### ISSUE TITLE
Synchronise collection

### ISSUE THREAD

**Issue by bricas** [jesus2099/konami-command#173]
It may be a new button next to Load/Reload or something, but the idea is this:

I add new items to my collection almost every week. On my primary machine, adding the item to the collection means it also gets highlighted.

However, I have a couple other machines that I use and I usually click "Load" to make sure the highlighting is up-to-date. The only problem is that it has to load _all_ of the entries (which is rapidly approaching the 1000 mark).

It would be nice if it could just skip over entries I already have in my local storage and just load the missing ones.

Thoughts?

**Comment by jesus2099** [comment]
It could be a new **synchronise** button that would load new releases and their stuff and unload removed releases and their stuff.
Good idea, @bricas.
But first, I will wait and see how metabrainz/musicbrainz-server#240 can speed up the normal buttons (it could skip the long one by one release loading you know).

**Comment by jesus2099** [comment]
Hey this PR is on beta server, I should even test it ASAP.

**Comment by jesus2099** [comment]
BTW if you click **Load**, it will add missing releases but will not remove releases that have been removed from the collection.
It seems **Re‐load** and **Load** buttons are not very self explanatory.

I will probably rename to <del>Re‐load</del> → <ins>Load</ins> and <del>**Load**</del> → <ins>**Append**</ins> (mostly useful to load multiple collections), then.

**Comment by jesus2099** [comment]
Hey @bricas I wanted to record the collection loading panel for the last time before coding the super fast loading, as a souvenir animateg GIF.
But it’s impossible actually to load my [678 releases](http://musicbrainz.org/collection/f0574792-6af6-481e-8b2f-d5ea9fc59c4d), it makes lots of 503 errors and eventually stops trying.
I tried at home and then at the office, the same.
Do you have the same problem?

**Comment by bricas** [comment]
Yea. This was actually part of the reason why Ive requested a sync feature. I thought it was only happening to me though :)

**Comment by jesus2099** [comment]
Well sorry @bricas but I really have not enough time to make this one and the alternative #174 is blocked by Web Service being still _incomplete_, despite the latestenhancements.
COLLECTION HIGHLIGHTER was just created as a help that I still hope is temporary until genuine MBS support [MBS-3491](http://tickets.musicbrainz.org/browse/MBS-3491) is eventually provided.

**Comment by bricas** [comment]
:cry: ah well. thanks for trying, though! :smile:

**Comment by jesus2099** [comment]
I would have greatly appreciated this myself but it requires too much work. Sorry. 😩

**Comment by jesus2099** [comment]
I recently changed button label to **Append**.
I’ll try to make this **Append** button only fetch data for *new* releases.

**Comment by bricas** [comment]
Awesome! I just tried it out and it works great.

A full sync would be nice, but I remove things so rarely that just appending works 99% of the time.

Cheers!
