### ISSUE TITLE
Please add userChromeJS support

### ISSUE THREAD

**Issue by ardiman** [jesus2099/konami-command#18]
Hello,

if you change the querySelectorAll-string into:

``` javascript
var ujs = document.querySelectorAll("table.files tbody a.js-directory-link[title$='.user.js']:not(.j2gIUS), table.files tbody a.js-directory-link[title$='.uc.js']:not(.j2gIUS), table.files tbody a.js-directory-link[title$='.uc.xul']:not(.j2gIUS)");
```

even scripts for the firefox extension userChrome.js will be linked.

**Comment by jesus2099** [comment]
@ardiman, I am preparing a renaming of this user script (5947d2b2244ceab9a44ff46920e62727c368c5df).
Please **don’t do anything** special, you should not loose the stream of updates even with the future name. **Let the auto‐update do its job.**
Please tell me if you face any problems. :)
