### ISSUE TITLE
Server-selection menu runs off the screen

### ISSUE THREAD

**Issue by uklauer** [jesus2099/konami-command#183]
Unfortunately, the server-selection menu now runs off the screen:
![open server-selection menu](https://cloud.githubusercontent.com/assets/1127374/13980139/2096aade-f0dd-11e5-84b7-d9c171ef5c0d.png)

Could you align the sub-items to the right instead? Here is how that was done for the language selector: https://github.com/metabrainz/musicbrainz-server/commit/51c8050856b73836b6eedca18ee86b5be6a5da1f Alternatively, if the menu came to the left of the language selector, there would probably be enough space to leave it as it is.

**Comment by jesus2099** [comment]
![server_switch](https://cloud.githubusercontent.com/assets/1401086/13988190/24ffba92-f10b-11e5-84a7-bf7761556b86.PNG)

Oh, sorry.
I’ve only tested it in Opera, I thought it would have worked everywhere.
I will try the other browsers and fix.
Thanks for the link, it might be useful. :)

**Comment by uklauer** [comment]
> I also notice that it doesn’t close when I click its title…

Interestingly, that *does* work for me (in Firefox).
