### ISSUE TITLE
Resurrect “Always show all releases on Musicbrainz v1.0” by Naja Melan

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#186]
What do you think @najamelan ?
Would you mind if I took your idea (:star2:) back to life ?
I would do it differently (#185) but it would be same spirit.

(:star2:) [Always show all releases on Musicbrainz](http://userscripts-mirror.org/scripts/show/9456.html)

**Comment by jesus2099** [comment]
For this one, don’t change the link on :mouse: right click.

**Comment by najamelan** [comment]
Feel free to do whatever you want with any code I spread around ;)

**Comment by jesus2099** [comment]
Thank you, @najamelan! 😀👍
