### ISSUE TITLE
mb. ALL LINKS for other MB entities

### ISSUE THREAD

**Issue by Freso** [jesus2099/konami-command#187]
It would be great to have search links for e.g. Release to RYM, AllMusic, Discogs, etc. and similar for Works (to that classical work site, Second Hand Songs, SACEM, …), Places (WP at least, possibly GeoNames or other location dbs), etc.

**Comment by jesus2099** [comment]
This for the ticket @Freso, I thought it existed but no. 
My plan is that appropriate links appear where they should.
So it sounds like this, doesn’t is?
If your auto link contains a parameter that can be matched on current page, it will display.

We used to have release auto links (#45) but this feature is even more general.

**Comment by y-van-z** [comment]
There is a bit of work in progress at [y-van-z/konami-command/all-shook-up-links/mb_ALL-LINKS.user.js](https://github.com/y-van-z/konami-command/commits/all-shook-up-links/mb_ALL-LINKS.user.js). Hidden links, edit buttons and Wikipedia links are already shown for all entities since y-van-z/konami-command@79d79eb16169768002b72754df1a2734165d204c. Next step is to show search links for all entities, that would address this issue.

**Comment by jesus2099** [comment]
Super, @y-van-z, thanks very much!

For artists, we have [those parameters](../blob/7245fd8e8ffb9769acf3c02d33e3a63fb373a3a2/mb_ALL-LINKS.user.js#L37-L40):

    // %artist-id% (MBID)
    // %arist-name%
    // %artist-sort-name%
    // %artist-family-name-first%

I don’t know what you plan to provide for other entities (you can provide nothing or minimal for a start, we can add later) but for releases, we used to have only [those parameters](06dacc3f6c798e40b80b4b0e9b461b65c5f497ff):

    %release-barcode%
    %release-cataloguenumber%
    %release-cataloguenumber-part1%
    %release-cataloguenumber-part2%

I don’t know how better named could be the last 2. :)

The principle is that when ALL LINKS run, it will compute take all and only those autolinks that use a parameter starting with `%currentEntytyType-` (beware of `%release-` in `%release-group-`).

But I will take care of supporting those if you just start by enabling ALL LINKS (hidden links) on entities.
You’re great. :+1:

**Comment by jesus2099** [comment]
I won’t work on this ticket as long as you do. :)

**Comment by y-van-z** [comment]
> I don’t know what you plan

I don't know either! It really depends on implementation glitches ahead. Name will be provided for sure and it will be easy to support any other parameter by simply adding it to a key/value object later on. But there is more to come in the next batch of commits. I will open a pull request once it solves this issue.

**Comment by jesus2099** [comment]
Good luck understanding all my crappy code! :blush:

**Comment by jesus2099** [comment]
FYI @y-van-z I have just pushed a very small fix to ALL LINKS in master branch (version `2016.6.6`).

**Comment by jesus2099** [comment]
I guess @y-van-z you are waiting to challenge the stability of your changes but once you feel it is ok I would very welcome a PR as your commit descriptions already sound seductive (and before mixing too many topics together as well). :thumb up: :)

**Comment by y-van-z** [comment]
Sorry for the long awaiting time, I swear I did not try to implement a coffee machine! :coffee: :wink: 
This pull request has no conflict with your fix bc113a9b59837e686e9ab5547c948becf00cb17a

**Comment by jesus2099** [comment]
Thanks, it’s superb.
I have commented over there on the requirement to keep the entity type in the token names.

**Comment by y-van-z** [comment]
No at all, it is just a very nice extra feature which is usually not listed in the original specifications.
Yet there are real implementation examples: [video demonstration](https://www.youtube.com/watch?v=OHE9LgwZ1P4), see the :+1: of the thirsty man.

An English equivalent to _usine à gaz_ seems to be _white elephant_ for the unmaintainable aspect, and either _Rube Goldberg machine_ (in the US) or _Heath Robinson machine_ (in the UK) for the overly complex aspect, after the name of cartoonists.

**Comment by jesus2099** [comment]
PR #238 fixed this but @y-van-z has another ongoing `all-shook-up` branch that will implement all @Freso examples then we will close this ticket.

**Comment by jesus2099** [comment]
For SACEM link, it’s now https://sigried.sacem.fr/oeuvres/oeuvre/printOeuvre.do?cocv=7300202211 (cf. #263).

**Comment by jesus2099** [comment]
We’ll wait for #244.

**Comment by jesus2099** [comment]
ALL SHOOK UP LINKS is finally released!
Thank you very much @yvanzo!

**Comment by yvanzo** [comment]
Thanks a lot to you @jesus2099 for your hard work at reviewing, updating and integrating this branch!
