### ISSUE TITLE
[request] Script fetching ISRCs from HMVdigital.com release pages

### ISSUE THREAD

**Issue by Lotheric** [jesus2099/konami-command#188]
See : https://community.metabrainz.org/t/fetching-isrcs-from-spotify/20910/9?u=lotheric

**Comment by jesus2099** [comment]
Do other browsers have [user CSS](http://opera.com/docs/usercss) ?
cf. jesus2099/settings@70f2cc51ae41ea4d8ef3971820d0f8300f4bdaa9#diff-44ab0d020b20eee3df2f8caf61366e12

**Comment by jesus2099** [comment]
Can you use that user CSS, @Lotheric?
User CSS is really better than user JS for this kind of stuff.

**Comment by Lotheric** [comment]
I guess I need an extension for it ? I'm using Chrome for Windows.

**Comment by Lotheric** [comment]
I'm at work at the moment. I see an extension called "Stylish" for Chrome. I'll try that tonight :)

**Comment by jesus2099** [comment]
Maybe this [User CSS extension](https://chrome.google.com/webstore/detail/user-css/okpjlejfhacmgjkmknjhadmkdbcldfcb)?

**Comment by Lotheric** [comment]
It works with [Stylish](https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en-US)! 

Thanks, it's awesome !!

**Comment by jesus2099** [comment]
You’re welcome. :)

**Comment by jesus2099** [comment]
Fixed elsewhere by [user CSS](/jesus2099/settings/commit/70f2cc51ae41ea4d8ef3971820d0f8300f4bdaa9#diff-44ab0d020b20eee3df2f8caf61366e12).
