### ISSUE TITLE
make EASY_DATE® better experience

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#20]
- [x] keep current loose `d/m/y|y/m/d` date recognition of EASY_DATE (and use it everywhere #19)
- ~maybe remove the secret <kbd>c</kbd> (copy) date hotkey, or maybe not~
- ~show two larger (than `YYY+`) **unique** date fields and brand them (`placeholder`) `EASY_DATE` instead~
- [x] stop hiding genuine `YYYY`
- ~if `css` possible in the limited AR popup space, **show genuine fields**~
- #875

**Comment by jesus2099** [comment]
Hey, I’ve tried nikki’s script again and now it also works in relationship editor popups and release editor, I’m letting you know that too !
**IMO there is eventually absolutely no more need for EASY_DATE !**
@pankkake, @zas, do you see any reason why I wouldn’t **drop EASY_DATE** feature in favour of [paste-a-date](https://bitbucket.org/96187/userscripts/src/master/paste-a-date/), now ?
I have turned EASY_DATE off for the moment in my own settings, happily using nikki’s greater script again, myself.
I don’t exactly know who [Keju](http://userscripts-mirror.org/topics/193018) is… :)

**Comment by laurentb** [comment]
I think it was missing in Events relationships but you can't add dates on them now. I haven't found a place where it was missing lately.

**Comment by pankkake** [comment]
I did not notice any issue with Paste-A-Date lately.

EASY_DATE has the "c" feature but I don't use it much.

**Comment by jesus2099** [comment]
My only remaining lacks in it are now end=begin feature indeed, and also I have to click more often because of the usa date format support, that I never use but that is conflicting with many dates.
But it's so much better to have one great script, especially now that it is hosted in bit bucket.
So as you are ok too, I will close EASY_DATE. :)

**Comment by Freso** [comment]
Maybe detect whether Paste-A-Date is present and disable EASY_DATE? Paste-A-Date does not work for all date forms, but EASY_DATE seemed to work fine for those that PAD didn't.

**Comment by jesus2099** [comment]
Detection is not usually trivial as PAD can be ran afterwards SUPER, staying undetected…
But probably that « _show {…} **unique** date field(s)_ »  (3rd point of original post) would fix this incompatibility.

**Comment by jesus2099** [comment]
Hi @Freso.
I made a change that should enable simultaneous use of Paste-A-Date or any other date related script.
But I didn't find a working version of Paste-A-Date! to test... :-/

**Comment by jesus2099** [comment]
PAD should be OK now: #40

**Comment by jesus2099** [comment]
I move the only remaining unimplemented feature Add support for date span (2 dates) pasting to #875 and close this big old mish mash ticket.
