### ISSUE TITLE
SUPER MIND CONTROL: Hide ratings

### ISSUE THREAD

**Issue by pankkake** [jesus2099/konami-command#21]
Since you added an option to move ratings, could you add one to hide all ratings?

I've done a few things with a custom CSS, but it doesn't work reliably depending on the artists as the number of columns isn't always the same and they have no proper CSS classes :(
Here's my current usercss: https://gist.github.com/pankkake/f2693e917ebbfc06bd7a

**Comment by pankkake** [comment]
I guess I should do it myself one day. I just did not want to fiddle with JavaScript :(

My overall goal is to fit as much info as possible on a small window.

**Comment by jesus2099** [comment]
I did not mean I would not do it. :)
I will do it. I don't have so much time, this is why non priority issues stay open for long.

**Comment by jesus2099** [comment]
Hi @pankkake, I did this for you.
It works with my browser(s) but please tell me if it’s OK for you too or if it’s missing anything. :)

**Comment by pankkake** [comment]
It works, thanks a lot!
As to why do it, it's because my browser screen is narrow so I don't have much space for each column.

**Comment by jesus2099** [comment]
No problem, I already understood (despite my comment) that it’s good to hide what you never need/use. :)

**Comment by jesus2099** [comment]
Maybe I will abandon this feature next time it's broken...
