### ISSUE TITLE
Alt+Click conflicts window move in Linux

### ISSUE THREAD

**Issue by pankkake** [jesus2099/konami-command#22]
But CTRL+ALT+Click and all other works. I have the issue with both Firefox and Chromium, under Linux.

**Comment by jesus2099** [comment]
After the loss of pankkake, I went through this issue.
In fact it's the same for me now that I am using Debian Xfce where Alt+click stands for a shortcut for window move.
I don't know if I want to deactivate this default Xfce shortcut or rather change my script for compatibility with all the people who will not want to change default Xfce.

**Comment by jesus2099** [comment]
Fixed by using `Ctrl`+`Shift`+click instead of `Alt`+click in #736.
