### ISSUE TITLE
navigator.languages regression

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#231]
I copy @y-van-z’s [remark](../commit/f3f2ef5e48fec81eadf6fce8da7d7f78ef481a1d#diff-8a6e63ef5b5a21e5b708df53d9731b9aR612) here:

> 1. The above line introduces duplicates when the `outputLanguages` array already contains the two-letters language code.
> Example: `["pt-BR", "pt"]` → `["pt-BR", "pt", "pt"]`
>
> 2. It does not deal very well with the `["zh-min-nan"]` locale.
> Example: `["zh-min-nan"]` → `["zh-min-nan", "zh", "zh"]`
>
> 3. Since it is done out of the `guessNavigatorLanguages` function, it can not be previewed from the prompt.

**Comment by jesus2099** [comment]
It’s possible. I haven’t tested carefully, I only made this change to allow my browser `en-GB` setup to display the `en` links.
I’ll test it, notice I made further change after that commit, so maybe, parts are fixed already.
What would be the correct spit(s) for `zh-min-nan`? Is `["zh-min-nan", "zh"]` or should it be something else?

**Comment by jesus2099** [comment]
That `splice` line was removed in [a later commit](../commit/dba70ebe9ba6def658203397404f567a09408a85#diff-8a6e63ef5b5a21e5b708df53d9731b9aL612) and replaced by a `splitLanguages()` function that, maybe, partially fixes wht you have spotted.
I will check that.

**Comment by y-van-z** [comment]
`["zh-min-nan", "zh"]` should be fine.
There is a ["zh-min-nan" Wikipedia](https://phabricator.wikimedia.org/T30442), just like ["en-x-simple" Wikipedia](https://phabricator.wikimedia.org/T110190) has been proposed.

**Comment by jesus2099** [comment]
1. I have tested `["pt-BR", "pt"]` will remain as is.
2. I cannot reproduce: In Opera I can set any language but `navigator.languages` is not supported. In Firefox, where `navigator.languages` is supported, I cannot really add user defined values, such as `zh-min-nan` in my favourite languages.
3. Users can see how browser languages are expanded in the prompt dialogue (dba70ebe9ba6def658203397404f567a09408a85). Is it enough?

Can you tell me, @y-van-z, if points 2 and 3 are still a problem? :)

**Comment by y-van-z** [comment]
1. Not for me, at least not in the prompt preview of `navigator` variable.
2. You can set it directly in the `configure wikipedia languages` prompt.
3. Not really, the prompt dialogue preview no more shows what is really detected.
