### ISSUE TITLE
Better issue management

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#232]
- Maybe have a look at https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/
- Priority is missing, I am not satisfied with my dated milestones ☞ Maybe have 3 floating milestones (now, soon, later) instead (or labels? maybe my urgent label is enough?)
- In progress ☞ assign

**Comment by y-van-z** [comment]
I think that you are doing well with current labels and milestones.
- There are good practices in it, but you already follows most of them, others apply to larger projects.
- Priority is already handled by your _urgent_ label. Milestones additionally allow for time expectation (_within days_, _within months_, _not before months_ for instance). The only time I beat you was on an issue not associated to the ongoing milestone.
- It can already be seen from referenced commits.

**Comment by jesus2099** [comment]
@yvanzo > _The only time I beat you was on an issue not associated to the ongoing milestone._

I don't understand this line. 🤔 
But you are right, I don't need to change. 
Except as you suggest too, I could rename my milestones from _millésimes_ (YYYY) to _within days_, _within months_ and _not before months_.
I will only keep that in mind at the moment, because I haven't really used my milestones any more.
