### ISSUE TITLE
MASS MERGE RECORDINGS: Allow negative track number as a start

### ISSUE THREAD

**Issue by pankkake** [jesus2099/konami-command#25]
Right now, you can chose to start to merge tracks on track 1, 2, 3, etc.
However, there are some times when I also want to "go up" instead of "go down"; the solution is to do the same merge on the other release (as going up on one means going down on the other). However this requires more copy/pasting and keeping two tabs open.

I'm not sure how it could be presented on the interface though.

**Comment by jesus2099** [comment]
Good idea !
I use the same workaround, it’s true that it’s not so convenient, but I didn’t get that idea. :)

**Comment by jesus2099** [comment]
I added this, I hope it will not regress something else. :)

**Comment by monxton** [comment]
This feature is brilliant! Thanks to Pankkake for the idea and Jesus for implementing it.

**Comment by jesus2099** [comment]
I want to thank my parents too, without whom this feature would not be there.
Seriously : You’re welcome. :)
