### ISSUE TITLE
EUC-JP and Shift JIS searches started to act strange

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#253]
Between https://github.com/jesus2099/konami-command/issues/217#issue-154879894 and https://github.com/jesus2099/konami-command/issues/217#issuecomment-230111398 the spaces and everything else have started to be encoded strangely.

**Comment by jesus2099** [comment]
Now neither Joshinweb nor CDJournal have a functioning search from ALL LINKS.

**Comment by jesus2099** [comment]
OK I found the  problem. :relieved:

`encodeURIComponent` is [now mistakenly performed even on `<form>` `<input>`](https://github.com/jesus2099/konami-command/commit/66dc11534b9200d02cc56027a1198e0beeed67cf#diff-8a6e63ef5b5a21e5b708df53d9731b9aR625) whereas, before, [it was hopefully not](https://github.com/jesus2099/konami-command/commit/66dc11534b9200d02cc56027a1198e0beeed67cf#diff-8a6e63ef5b5a21e5b708df53d9731b9aL419).

**Comment by jesus2099** [comment]
FTR It came since my merge of #238.

**Comment by y-van-z** [comment]
This is a straightforward fix based on your [above comment](https://github.com/jesus2099/konami-command/issues/253#issuecomment-233961177), I did not test it thoroughly, example MB artists would be welcome.

**Comment by jesus2099** [comment]
Hey @y-van-z, thank you!
I was actually already fixing it but as I have so little time, I had to stop in the middle of doing it.
Now I have done it (in a less clean way) and am about to test it a very little bit. :)
Thanks again for your huge #238, BTW. :bow:

**Comment by jesus2099** [comment]
What a relief! :sweat: 
It was bugging me (I had to copy paste stuff manually) for some time but never took the time to check if it was my script or their server changes.
