### ISSUE TITLE
kasi. PLAIN TEXT  please update

### ISSUE THREAD

**Issue by michek093538** [jesus2099/konami-command#26]
update
http://petitlyrics.com/lyrics/1015204        /kashi/ changed /lyrics/

new site
joysound.com/ex/search/karaoke/_selSongNo_119001_songwords.htm
j-lyric.net/artist/a057818/l031ba7.html

**Comment by jesus2099** [comment]
There is no need for J-lyric as they don’t try to block selection and copy.

**Comment by jesus2099** [comment]
By the way, thank you for the report !

    1. I have fixed プチリリ.
    2. I have added J-Lyric.net right click menu unlock.
    3. I have added JOYSOUND support.

**Comment by michek093538** [comment]
thank you!

but プチリリ not drive ....

**Comment by jesus2099** [comment]
It works for me, what is your browser Michek ?

**Comment by michek093538** [comment]
I use Chrome version 39.0.2171.95 (64-bit)

I'm amateur writer,I do not know a lot about this.. sorry

**Comment by jesus2099** [comment]
Thanks Michek, it should be fixed again now. :)

**Comment by michek093538** [comment]
thx!
Marvelous!!
