### ISSUE TITLE
Inline SACEM links

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#263]
Like I do inline JASRAC links.

**Comment by y-van-z** [comment]
The current SACEM links are defunct, see pull request #244 for updated links.

**Comment by jesus2099** [comment]
Yes, good idea to wait for some new ALL LINKS tokens instead of specific code! Like, for instance `%work-attribute-type%` and `%work-attribute%` or %work-attribute-name%` and `%work-attribute-value%`…

What I meant actually is, if you go to this [SPRING SNOW](//musicbrainz.org/work/4dee65ea-fb9f-4eb4-bef5-3c890c4d90f4) wong (work) and have the appropriate script switched on (*jasrac import*, I guess), you will see this (in the sidebar):

> **Work information**
> - **Type**: Song
> - **Lyrics Language**: [Japanese](//musicbrainz.org/search?query=lang%3Ajpn&type=work&method=advanced&limit=25)
> - **ISWC**: [T-101.936.825-1](//musicbrainz.org/iswc/T-101.936.825-1)
> - **JASRAC ID**: [157-0845-4](http://www2.jasrac.or.jp/eJwid/main.jsp?trxID=F20101&WORKS_CD=15708454&subSessionID=001&subSession=start)
> - **SACEM ID**: 2588781511

You see that the **SACEM ID** is not linking to anywhere.
There I would by this feature make each **SACEM ID** (`<dd class="work-attribute work-attribute-sacem-id">`) a link as well as each **JASRAC ID** (`<dd class="work-attribute work-attribute-jasrac-id">`) is already turned into a link:

> - **SACEM ID**: [2588781511](//repertoire.sacem.fr/droit-auteur/-/2588781511?query=&filters=)

---

Maybe you were thinking about the SACEM search link… Now I remind this.
So, it does not work any more? I will fix that too if it is NG…
Don’t worry, I have not forgotten your PR at all, it’s always on my mind, I’m in the middle of merging it but I have so very little time nowadays. But I’ll do it anyway before changing ALL LINKS any further. :)
I have not done any serious github since then and won’t do any before your PR is merged. :bow:

**Comment by jesus2099** [comment]
My previous *release event tools* script was turning catalogue numbers, barcodes, etc. into links.
Like each JASRAC ID are turned into links.
I think, if ALL LINKS has only one matching rule for a token, it could turn the text into links.
Or one could define which search rule is **the** default rule that will replace the the text.
Anyway, that’s for later.

**Comment by y-van-z** [comment]
> Maybe you were thinking about the SACEM search link… Now I remind this. [...] Don’t worry

Yes, I meant SACEM *search* links (I do not use jasrac things), it never worked for me, I assume that it has been down for months. Don't worry either, I was just giving info on SACEM links.

**Comment by y-van-z** [comment]
In your above example:
- the JASRAC link returns an error message. 接続が切断されました
- the SACEM link points correctly to the corresponding SACEM work.

It seems that SACEM IDs can be reliably turned into links.
How about integrating this directly to the MusicBrainz server?

**Comment by jesus2099** [comment]
> the JASRAC link returns an error message. 接続が切断されました

Because direct links are blocked, unless you use a *jasrac direct links* script… ;)

> How about integrating this directly to the MusicBrainz server?

Ultimately yes, would be cool. :+1: 

The only problem is that those sites can change, they don’t even imagine we are hot‐linking them. :)

- [SACEM](https://repertoire.sacem.fr/) did that overhaul.
- [JASRAC](http://www2.jasrac.or.jp/eJwid/) is very stable but requires an auto‐login script
- [Music Forest](http://www.minc.gr.jp/db/) has turned into an account‐only system since 2013-05-07

They don’t intentionally expose a stable API like some sites do (Wikipedia, etc.).

**Comment by y-van-z** [comment]
Yes, even after an overhaul, the current SACEM site is not very satisfactory, I wouldn't be surprised should it soon change again. Let's hope a public stable API instead.

**Comment by jesus2099** [comment]
Speaking of it, previous SACEM site did not even allow to link to work pages through their ID but through their ISWC. So ISWC‐less works could not be direct linked, except by linking to a specific narrow enough search to get only one result. :)
Now we can link to SACEM ID, that’s cool. I hope it will remain.

**Comment by jesus2099** [comment]
[MBS-7361](http://tickets.musicbrainz.org/browse/MBS-7361) added `.work-attribute-jasrac-id` and `.work-attribute-sacem-id` to those attributes, where I want to create the link.
I should check if I already use `.work-attribute-jasrac-id` or if I still use some clumsy pre‐**MBS-7361** parsing.

**Comment by jesus2099** [comment]
Jasrac links (COCV) have changed.

**Comment by jesus2099** [comment]
Now it’s https://sigried.sacem.fr/oeuvres/ → https://sigried.sacem.fr/oeuvres/oeuvre/rechercheOeuvre.do?titre=letter+to+hermion&tiers=bowie → https://sigried.sacem.fr/oeuvres/oeuvre/printOeuvre.do?cocv=7300202211 → **7300202211**

**Comment by jesus2099** [comment]
Thanks to SURIV in https://musicbrainz.org/edit/46296350

**Comment by jesus2099** [comment]
Now legacy `sigried` server is down, there is no way to hot link with work ID any more.

BTW I am now using MBS-7361 `.work-attribute-jasrac-id` in https://github.com/jesus2099/konami-command/blob/8dc9ee63dbbc0d954bbd75c2a6d47acf889df5ab/jasrac-mb-minc_WORK-IMPORT-CROSS-LINKING.user.js#L474 .
