### ISSUE TITLE
Red reload after error appears in two different places

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#267]
:warning: Maybe it’s invalid after #244 so I will not search before this PR merge: [![mb_ALL-LINKS bug 503.gif](http://i.imgur.com/NdZQlAit.gif)](http://imgur.com/NdZQlAi)

**Comment by y-van-z** [comment]
I confirm this is fixed in PR #244 as well.

**Comment by jesus2099** [comment]
Great to hear, @y-van-z, thanks ! :)
