### ISSUE TITLE
MASS MERGE RECORDINGS not working after MBS-3841

### ISSUE THREAD

**Issue by Freso** [jesus2099/konami-command#29]
E.g., merging recordings from https://beta.musicbrainz.org/release/5231db37-3b4a-43d3-af15-1f524a35f147 to https://beta.musicbrainz.org/release/e815a245-4e64-46df-8413-fe7983673f13 (currently only on beta, but will go live on production at next release - or earlier, as it may get included in a hotfix)

**Comment by jesus2099** [comment]
Thanks Freso,
It seems INLINE STUFF is broken too.
I wonder what’s up with those releases… do you know a ticket link so I could roughly understand what was done (I guess either the layout changed or the tracklist rendering was delayed).

**Comment by jesus2099** [comment]
It seems that after [MBS-3841](http://tickets.musicbrainz.org/browse/MBS-3841) fix, links to recordings are now back to full URL with host (`http://mb.org/recording/mbid`).
URL without host (`/recording/mbid`) was (quite recent but) better, IMO. 
I wonder if this drawback is intentional or just an oversight…

**Comment by jesus2099** [comment]
I will wait and see if it’s kept in live MBS…
Until then, as quick workaround, you can search replace `href^='/` → `href*='/` in both INLINE STUFF and MASS MERGE (two occurrences in each).
Tell me if you have more info. :)

**Comment by Freso** [comment]
http://tickets.musicbrainz.org/browse/MBS-3841
https://bitbucket.org/metabrainz/musicbrainz-server/pull-request/1375/mbs-3841-loading-releases-or-release/diff

**Comment by jesus2099** [comment]
I’m working on it, it’s eventually more drastic… 
Maybe we will loose :

* video icon
* data track icon
* track length in milliseconds
* pending edit status
* etc. ?

I hope only temporarily but I will have to make a request to the normal pages AND to the web services to get as much info as before on both local and remote releases.

**Comment by jesus2099** [comment]
For info, I am **not** currently working on making **MASS MERGE RECORDINGS** compatible with new layout…

I first repaired it without all the matching features (track times, track names, etc.), then I started re‑adding the features but then I have no time at the moment.

There is also **PLAIN TEXT TRACKLISTS** that would require to be changed but I have just repaired **INLINE STUFF** for the moment.

**Comment by jesus2099** [comment]
Here is a link to [**watch this issue for people without github account**](http://pipes.yahoo.com/pipes/pipe.info?_id=ae40e6520c753d229bfa5de37c0c79ce) and be informed of any news concerning this issue.
It’s a Yahoo pipe where you can subscribe to an RSS feed (among other options).

**Comment by jesus2099** [comment]
splitting MBS-3841 related tickets from here :

* INLINE STUFF was #30 
* TRACKLIST_TOOLS is #35
* PLAIN TEXT TRACKLISTS is #36

**Comment by Freso** [comment]
What issue is tracking a fix for MASS MERGE?

**Comment by jesus2099** [comment]
I have made it work without fixing the regressions.
I will close this ticket once I have listed all the regressions to fix (some require calling both release page and web service so it will be long to fix).

**Comment by jesus2099** [comment]
Here are some regressions I know :
The simple ones are #46 #47.
The maybe simple ones are #48 #49 #51 (but they would all be rewritten if/once an additional WS call is made for milliseconds in #48).
The one that will be difficult to overcome is #50 (remote release of more than 10 mediums).
