### ISSUE TITLE
Migrate from //notlob.eu/isrc/ to //www.kepstin.ca/magicisrc/

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#292]
I have trouble with the former not updating for new releases.
The latter seems to be always up to date but is not MASS enabled either.
A very small change in the script allowed it to work on @kepstin’s `magicisrc`, but I had dumped this change uncommitted, as it was exclusive and @96187’s `isrc` wouldn’t run any more (but now I think I can totally make the switch for good).

**Comment by kepstin** [comment]
FYI, I've put the magicisrc code up on github now. I'm tracking the mass paste feature at kepstin/magicisrc#1

**Comment by jesus2099** [comment]
That’s great to hear!

**Comment by jesus2099** [comment]
For my record and for my other computer, here is the convenient **bookmarklet** I use for that work in progress:

**magicISRC this!**: `javascript:var mbid=location.pathname.match(/^\/release\/([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/);if(mbid)void(open("https://rawgit.com/jesus2099/magicisrc/%25231-support-pasting-multiple-isrcs/index.html?mbid="+mbid[1]));
`

Look at this @kepstin, it’s super convenient. ;)

**Comment by jesus2099** [comment]
Closing for #74 as the PR is currently stalled but I can still use the PR bookmarklet in the mean time.
