### ISSUE TITLE
INLINE STUFF: not working on beta

### ISSUE THREAD

**Issue by Hawke** [jesus2099/konami-command#30]
the INLINE STUFF script is not showing acoustIDs on beta, at present.

**Comment by jesus2099** [comment]
Thank you Hawke, actually I fixed it already but not released it, as beta is still not on live environment.
Also I fixed INLINE STUFF in a same branch as MASS MERGE is benig fixed but MASS MERGE will most certainly not be ready for launch… I don’t know, maybe I will have to do some git things to release INLINE STUFF out of this branch alone if I can manage to do this…
