### ISSUE TITLE
USER_STATS’s “Total” edits link will break on special characters

### ISSUE THREAD

**Issue by Freso** [jesus2099/konami-command#300]
"Total" link will break on special characters. E.g., [https://beta.musicbrainz.org/user/Mario%20M%C3%BCller](https://beta.musicbrainz.org/user/Mario%20M%C3%BCller)

**Comment by jesus2099** [comment]
Thanks @Freso, I confirm bug with Firefox and Chromium, indeed.

**Comment by jesus2099** [comment]
Yes, @Freso, [there is a wonderful reward](https://chatlogs.metabrainz.org/brainzbot/musicbrainz/msg/3761021/) for submitting 300<sup>th</sup> issue !

![issue300](https://cloud.githubusercontent.com/assets/1401086/21347756/4aec0ed4-c6aa-11e6-9e42-b17bfc6716fc.png)
