### ISSUE TITLE
[script suggestion] Show area flags that aren't countries (i.e. Québec)

### ISSUE THREAD

**Issue by Lotheric** [jesus2099/konami-command#304]
Since MB doesn't allow regional flags (they're using some ISO country list), I would like to use a script to show the flag of Québec within MB.

https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Flag_of_Quebec.svg/16px-Flag_of_Quebec.svg.png

16x11 pixels would be alright I think.

The script could be expanded for other flags that MB users want.

**Comment by jesus2099** [comment]
Thanks for the suggestion !
I would display Québec and Bretagne. ;)
But honestly, I don’t know when I would do this, yet.

**Comment by Lotheric** [comment]
Hey jesus !

I found nikki's old script : http://userscripts-mirror.org/scripts/review/38668

and modified it for Quebec and it mostly work \ o /

just letting you know :D

**Comment by jesus2099** [comment]
Great, @Lotheric!
Now I remember this one, indeed. :)
