### ISSUE TITLE
Highlight included release groups

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#310]
An easy part of **SYSTÈME BALÈZE AVANCÉ™** (#257) where loading [SANS PLUS ATTENDRE / À TÂTONS / TOUJOURS MOI](https://musicbrainz.org/release/067b358f-f16c-4661-86f1-4489e3c2fd4c) for highlight should also highlight release groups (RG) that are linked as included to [its RG](https://musicbrainz.org/release-group/76b3395d-e1ed-491b-a83e-c1c25cf7b0f5):

- [SANS PLUS ATTENDRE](https://musicbrainz.org/release-group/4866480c-0d11-37bb-9947-92abc19f3a09)
- [À TÂTONS](https://musicbrainz.org/release-group/0a927a10-7414-3663-8382-94176e242638)
- [TOUJOURS MOI](https://musicbrainz.org/release-group/0f933341-b7e7-3e13-9596-0a3201ea7d9c)

**Comment by jesus2099** [comment]
[OUTSIDE / EARTHLING / HOURS / HEATHEN / REALITY](https://musicbrainz.org/release-group/98e078fe-37d9-43f7-8bb4-96526727c4e0)
------------------------------------------------------------------------

- [EXCERPTS FROM OUTSIDE THE NATHAN ADLER DIARIES : a hyper cycle](https://musicbrainz.org/release-group/f05647bf-86a7-3e6e-872a-20eb465be0a5)
- [EART HL I NG](https://musicbrainz.org/release-group/9a723e6e-2ede-371b-88bf-396cc362d77b) ;)
- [‘hours…’](https://musicbrainz.org/release-group/e8a94ea7-8466-389e-830a-d356801ca68c)
- [<del>HEATHEN</del>](https://musicbrainz.org/release-group/fed49206-4869-307d-9bfa-08109424cb73) ;)
- [REALITY](https://musicbrainz.org/release-group/0f9d1be4-e975-39e9-a5ee-867c87824f42) (already highlighted individually)

**Comment by jesus2099** [comment]
No relationships available yet for release to releases or release groups:

[莎木 Shenmue Orchestra Version](https://musicbrainz.org/release/8fc541fb-7601-4a02-b859-b1d9789ddde7) release
--------------------------------------------

- https://musicbrainz.org/release/eaa1d53e-5d52-43fb-b337-d26c73dafdf5
- https://musicbrainz.org/release/d2ebaf30-ce5c-429e-81ed-de95a97fc44f
- https://musicbrainz.org/release/db35a9f4-ce7f-47ff-9fc1-465fcb9b2ea7

**Comment by bricas** [comment]
👍  to this feature.

The Police's [Message in a Box](https://musicbrainz.org/release/35a9ec45-b8b2-4ef5-aba6-b872a84ee8e2) is another good example of the "**includes**" relationship .

**Comment by jesus2099** [comment]
I am missing the `release-group-level-rels` option in `/ws/2/release/<mbid>?inc=` web service.

https://musicbrainz.org/ws/2/release/eae52693-c8f9-422b-93c7-9630d3d14832?inc=release-groups+recordings+artists+artist-credits+labels+recording-level-rels+work-rels OK but
https://musicbrainz.org/ws/2/release/eae52693-c8f9-422b-93c7-9630d3d14832?inc=release-groups+recordings+artists+artist-credits+labels+recording-level-rels+work-rels+release-group-level-rels NG.

**Comment by jesus2099** [comment]
https://musicbrainz.org/ws/2/release/eae52693-c8f9-422b-93c7-9630d3d14832?inc=release-groups+recordings+artists+artist-credits+labels+recording-level-rels+work-rels+release-group-level-rels is now no errors but I see only empty array in release group `relations` property.

Oh I must include both `release-group-level-rels` and `release-group-rels` now it works! I do see the included release groups!!

https://musicbrainz.org/ws/2/release/eae52693-c8f9-422b-93c7-9630d3d14832?inc=release-groups+recordings+artists+artist-credits+labels+recording-level-rels+work-rels+release-group-level-rels+release-group-rels&fmt=json

I don't know the difference between them but if I include only one or the other, I get no relations.

**Comment by jesus2099** [comment]
This can be added in initial loading and in dynamic loading, no need for the **SYSTÈME BALÈZE AVANCÉ**™ system.

**Comment by kellnerd** [comment]
> I don't know the difference between them but if I include only one or the other, I get no relations.

I think the difference is the following:
* `release-group-rels`: loads relationships **between a RG** and the requested entities *)
* `release-group-level-rels`: also loads relationships **for the parent RG** and not only for the release itself

*) This is only the release by default (which has no RG-rels as there are [no release-RG rel types](https://musicbrainz.org/relationships/release-release_group)), but you can also include rels for the release's RG (such as RG included in RG) with the `release-group-level-rels` include parameter.

**Comment by jesus2099** [comment]
Yes, thanks @kellnerd!
I understood it too, after writing this comment, as I was going on planning my changes on paper.
I understand it each time I have to, but it does not stay in my mind, noce I have updated my code. :)

**Comment by jesus2099** [comment]
@kellnerd,

I have added this feature to my beta version (being migrated to super fast loading system + works with all huge releases of 501 tracks or more).
It works great!
But the script is not migrated completely yet (lacks dynamic updater and works fetching).

I have another feature I wish to add for compiled recordings, but I haven't thought too much about it yet because I am busy with the migration.
Can you tell me your advice on it?
Do you agree with it?

>Highlight compiled recordings #656

**Comment by kellnerd** [comment]
> I have another feature I wish to add for compiled recordings, but I haven't thought too much about it yet because I am busy with the migration.

Since you are already handling the included release groups, I would also handle "included" (compiled) recordings. But it might be possible that it makes the performance worse, in addition to the already used `recording-level-rels` (needed for the `work-rels`) you also have to include/load `recording-rels`. So I would definitely write the code and test the performance impact. I think it should not be too big since recording-recording rels are not that common.
