### ISSUE TITLE
Dynamic loader broken in Firefox

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#311]
Latest v2016.12.19’s `getStuff` does not find anything (else than current release).
OK in Opera 12.
Would probably not have happened with #64.

**Comment by jesus2099** [comment]
Steve reported IIRC same problem in Mac OS Safari.

**Comment by jesus2099** [comment]
Surprisingly enough, I had the same thing as Steve : full reload did repair the dynamic loader !
Now that office PC cannot reproduce bug any more, I have to save status (`localStorage`) on my home PC before fixing and compare states.

**Comment by jesus2099** [comment]
**WORK‐AROUND** : Reload your collection.

**Comment by jesus2099** [comment]
Steve reported that after it worked again for some time after full reload, it broke again.

**Comment by jesus2099** [comment]
Steve « _Did a full reload and looked like things were back to normal, but now I'm noticing that no artists are highlighted.  Weird._ »

**Comment by jesus2099** [comment]
@cheezmo, was this recurring issue maybe related to huge collection problem (#354)?

**Comment by cheezmo** [comment]
Absolutely.  I'm sure that the localStorage was full.

**Comment by jesus2099** [comment]
I thought so, thank you very much! :)

**Comment by jesus2099** [comment]
Fixed by #354.
