### ISSUE TITLE
Long lyrics not loaded any more in petit lyrics 

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#32]
https://greasyfork.org/en/forum/discussion/3042/long-lyrics-interrupted-at-petitlyrics-com

> [madauden](https://greasyfork.org/en/users/5741-madauden) posted: 1/30/2015
>
> **Long lyrics interrupted at Petitlyrics.com**
>
> Lyrics are interrupted when they are long enough at Petitlyrics.com.
> Open the following page and turn the script on and off to reproduce:
> https://petitlyrics.com/lyrics/1009898

**Comment by forrvalhalla** [comment]
Came here from the comments posted on greasyfork. Hopefully I am posting in the right place (I've never posted on GitHub before) but this still seems to be a problem as of December 2021. At around 15/16 lines it cuts off from the rest of the lyrics that are there normally.

**Comment by jesus2099** [comment]
Thank you for your report, @forrvalhalla.
It's the right place.

But I have to learn how my user script works again. I forgot how I coded this, years ago.
Hopefully, I will try within these 2 weeks.

**Comment by jesus2099** [comment]
Ach, it seems it will be impossible to fix.
The full lyrics are provided by `https://petitlyrics.com/com/get_lyrics.ajax`.
Then the content (a table of rows of text, URI encoded then Base 64 encoded).

Here is the decoder:

```js
// https://www.base64decoder.io/javascript/#javascript-generic-base64-decode-with-support-for-16-bit-encoded-utf-16-strings
// Javascript Generic Base64 decode with support for 16-bit encoded (UTF-16) strings
function base64DecodeUnicodeToString(str) {
    // Convert Base64 encoded bytes to percent-encoding, and then get the original string.
	var percentEncodedStr = atob(str).split("").map(function(c) {
		return "%" + ("00" + c.charCodeAt(0).toString(16)).slice(-2);
	}).join("");
    return decodeURIComponent(percentEncodedStr);
}
```

The request is made by `https://petitlyrics.com/lyrics/*` page in `POST` and `Content-Type: application/x-www-form-urlencoded; charset=UTF-8`.
With no query parameters but the **big problem** is that it should be requested with an `X-CSRF-Token`.
I don't know how to do that in user script. I don't think it is even possible, as the token has to be generated by server, I guess.

**Comment by jesus2099** [comment]
Maybe I can retrieve that `data[i].lyrics` and BTW I see that they do send a query parameter: `lyrics_id`.

```js
	$(document).ready(function () {
		eval("var a=\"sjn3hEe0VJLr-q_GZomfbBtIXyNgU4WxFuDHM8v5p2TS7AQdzi.C9lP1k6RcYaK+O@w\";var b=a.split(\"\").sort().join(\"\");var c=\"hrV2EEe3r77E00hrTe32Ve7Jh-3Ae2LJ\";var d=\"\";for(var e=0;e<c.length;e++)d+=b.charAt(a.indexOf(c.charAt(e)));var key = (\"\"+d+\"\");");

        var canvas = document.querySelector("#lyrics");
        var context = canvas.getContext('2d');
        var retinaSwitch = window.devicePixelRatio;
        var ratio = 2;
        
        if(retinaSwitch === 1) {
        	$('#lyrics').attr('width', 320);
        	$('#lyrics').attr('height', 2280);
        } else {
        	canvas.setAttribute("width", 320 * ratio);
        	var attribute_height = 2280 * ratio;
        	
        	canvas.setAttribute("height", attribute_height);// 
        	canvas.style.width = 320 + 'px';
        	canvas.style.height = 2280 + 'px';
        	context.scale( ratio, ratio );
        }
        
        
        $.post(
            "/com/get_lyrics.ajax",
            {
                lyrics_id:1009898
            },
            function(data, textstatus, XMLHttpRequest){

                var len = data.length;
                for(var i=0; i<len; i++){
                    
                    
                    context.font = "12px sans-serif";
                    context.fillText(Base64.decode(data[i].lyrics), 0, (20*i)+20);
                    
                }
                $(".ffrm").hide();$(".ffrm").show();
            }
        );
	});
```

There are some stuff I still want to check.

**Comment by jesus2099** [comment]
I made a new working version. 
I will fine-tune it and publish it soon.

**Comment by jesus2099** [comment]
I guess you don't really need it any more, @forrvalhalla, but it is fixed, at last! :D
