### ISSUE TITLE
SUPER MIND CONTROL Ⅱ X TURBO is too hardy

### ISSUE THREAD

**Issue by RocknRollArchivist** [jesus2099/konami-command#330]
Hi, 
I can't uninstall this script from Google Chrome.
I deleted TamperMonkey and all other extensions. No result.
I uninstalled Google Chrome and reinstalled it. But I see as before the line of script at bottom of 'Editing' (always highlighted) menu on Musicbrainz site..
How to kill it?
Thanks

**Comment by jesus2099** [comment]
As far as I can remember, there were two ways to install in Chronium, either with tampermonkey or the script as an extension.
Or maybe you have another script that appears in the **Editing** menu.
I think there **is** at least one other script that does highlight this menu.
I will check it out, uninstalling is normally done simply by deleting the script from the list.

**Comment by jesus2099** [comment]
It’s strange problem, it doesn’t happen to me.
Can you give me the version of chrome, of tampermonkey and of super turbo (click its menu item to see).
Uninstall chrome, even? Wow 😲
I don’t think my script has anything special.
It cannot resist more things than any other script.
You might be exciting another instance of chrome (from a different folder, check your links) each time or something. Or a different user, maybe?

**Comment by RocknRollArchivist** [comment]
I re-installed Windows, so no problem now ;-)

**Comment by jesus2099** [comment]
Let’s see if this problem reappears someday.
