### ISSUE TITLE
No delimiter for millions+

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#334]
https://chatlogs.metabrainz.org/brainzbot/musicbrainz/msg/3926932/ → https://musicbrainz.org/user/reosarevok

**Comment by jesus2099** [comment]
This delimiter code is used at several places (mass merge’s delimiter works better for instance) and should be shared through a library, maybe.

**Comment by Freso** [comment]
Is it part of REVIVE DELETED EDITORS? Aren't those stats part of SUPER MIND CONTROL's USER_STATS modules?

**Comment by jesus2099** [comment]
You’re right, @Freso! Thanks. :)

**Comment by Freso** [comment]
(Also, the delimiter is broken for millions+, not thousands. :))

**Comment by jesus2099** [comment]
Thanks again. :)

**Comment by jesus2099** [comment]
I think I will take the best code and move it to [NUMBERS](https://github.com/jesus2099/konami-command/blob/master/lib/NUMBERS.js) library.

**Comment by jesus2099** [comment]
No need for a lib, I’ll actually just use the genuine `number.toLocaleString(locale)` function.
Speaking of which, I notice that numbers are not localised in MBS.
1,000 is 1 000 in French and maybe 1.000 un Deutch.
