### ISSUE TITLE
mb. ALL LINKS: No search links for artists w/o "External links"

### ISSUE THREAD

**Issue by Freso** [jesus2099/konami-command#335]
When I go to https://musicbrainz.org/artist/1915e336-b318-46c6-ba7e-d7097782f09a I don't get any search links. Maybe because they don't have an "External links" section already?

ALL LINKS work fine on e.g., https://musicbrainz.org/artist/5a8cc407-7efb-4e94-9637-d5896395e754

(I also pinged you on IRC. Feel free to disregard that now. ;))

**Comment by Freso** [comment]
I see it on https://beta.musicbrainz.org/artist/fe0fff2a-f5eb-4145-b2ca-326c609e40e3 too, which also doesn't have an "External links" section.

**Comment by jesus2099** [comment]
Search links?
Are you using the version from #244’s branch?
This one: https://github.com/jesus2099/konami-command/blob/%23244_y-van-z_all-shook-up-links/mb_ALL-LINKS.user.js

**Comment by jesus2099** [comment]
Does not appear on https://musicbrainz.org/artist/57a10d3a-3d01-4eb2-9a78-c89d5926d06d either.

**Comment by jesus2099** [comment]
This does have an external link but still nothing is displayed (only 7 days to test as the link is being removed and the artist is being merged away).
