### ISSUE TITLE
TRACKLIST_TOOLS: “Set selected works’ recording dates” broken

### ISSUE THREAD

**Issue by ProfChris** [jesus2099/konami-command#338]
I have noticed that the set recordings date feature of this script has stopped working. Any chance of getting it repaired, as I find it a very useful feature

**Comment by jesus2099** [comment]
This menu item does not work any more, indeed:

> Set selected works’ recording dates ← **TRACKLIST_TOOLS**™

**Comment by jesus2099** [comment]
I should see how #70 was fixed.

**Comment by jesus2099** [comment]
It does not work at all but anyway I should not use `checkedWorks` as it’s a recording to work relationship that must be dated, not all occurences of that work.
