### ISSUE TITLE
All tracks show additional 30 minutes 

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#34]
I couldn’t reproduce that with same versions as him but fmera has this problem in Firefox 35.0.1, Greasemonkey 2.4.

When the track times display gets changed to milliseconds display, he obtains 30 minutes time too much on both local and remote tracks.

**Comment by jesus2099** [comment]
I still don’t see this happening.
The code has changed maybe it won’t happen any more for fmera either.

**Comment by jesus2099** [comment]
Now I can see it at [those edits](//musicbrainz.org/edit/39120345) (fmera again).

**Comment by jesus2099** [comment]
Again and asked for fmera’s help in https://musicbrainz.org/edit/43570372 as I never had this bug myself but he keeps having it all those… **years !**

**Comment by fmera** [comment]
now on Firefox 51 on OS X 10.9.5 (Mavericks)

tested with just GM 3.9 and mb. MASS MERGE RECORDINGS 2016.6.15 enabled, still same problem.

no problems even up until the moment i click the "mass merge recordings" button to activate the panel, but the track times all instantly increase by 30mins the moment i paste the url of the source release.

**Comment by jesus2099** [comment]
It must have something to do with OS X’s port of Firefox, then…
I don’t reproduce with FF 51 + GM 3.9 on Windows XP…

**Comment by jesus2099** [comment]
@fmera, could you test this new version there?
Click the above commit link (or f4c9ef37a39f102ce940351505286b94ad7b4c54), then [View](https://github.com/jesus2099/konami-command/blob/f4c9ef37a39f102ce940351505286b94ad7b4c54/mb_MASS-MERGE-RECORDINGS.user.js) then [Raw](https://github.com/jesus2099/konami-command/raw/f4c9ef37a39f102ce940351505286b94ad7b4c54/mb_MASS-MERGE-RECORDINGS.user.js) to install it.

**Comment by jesus2099** [comment]
Sorry, try this later one instead. :)

**Comment by fmera** [comment]
nope, still showing the +30min…

but it's no big deal, i've already gotten used to it after all these years!

**Comment by jesus2099** [comment]
Really?
What does it show instead of 19:06 in https://musicbrainz.org/release/491eb8fc-e358-4e84-8db6-e0409a6a7661 ?

**Comment by fmera** [comment]
49:06

**Comment by jesus2099** [comment]
@fmera, are you in a 30 minute shift time zone? What is your time zone?
Could you test this latest version (fa6e569ca2e08a16a9386c55e193818783a30988 → View → **Raw**) and copy / paste me what you get in the JavaScript console, please?

**Comment by jesus2099** [comment]
Just try the same release on itself: https://musicbrainz.org/release/491eb8fc-e358-4e84-8db6-e0409a6a7661 and then shift up and down the remote tracklist to check if both local and remote times are now correct or not. :)

**Comment by fmera** [comment]
will retry when i'm free, but it's no big deal really. don't waste too much tme figuring it out ;) anyway, i'm not in a "30min" time zone, full hour time zone. but what has time zones got to do with track times anyway? 

> then shift up and down the remote tracklist to check if both local and remote times are now correct or not. :)
don't think that will have any effect, as i've been doing that fairly often, to align tracklists between releases that are displaced. it won't cause the 30min error to go away.

will get back to you when i've tried the above fa6e569…

**Comment by fmera** [comment]
rejoice!!!! ;p 

your fa6e569 (2017.2.20) finally did the trick. the +30min bug is gone. how is it different from the latest regular update of your script?

**Comment by jesus2099** [comment]
Thanks for the test, I will integrate this change to the main branch, that was indeed updated recently (I don’t remember for what feature). :+1:

**Comment by jesus2099** [comment]
Hello @fmera,
Do you sometimes use the track time parser from SUPER TURBO in release editor?
It seems maybe it could have the same 30 minute problem:

https://github.com/jesus2099/konami-command/blob/22471b734cfd150bb4f0fdaadc9e3b8fce5620f4/mb_SUPER-MIND-CONTROL-II-X-TURBO.user.js#L1644

**Comment by fmera** [comment]
no, i don't have that script installed. good luck with the fix!

**Comment by jesus2099** [comment]
In the devtools, **Sensors** tab, I can stimulate being in a timezone with minute shifts (not only hours), like @fmera.

    AU	−1228+13050	Australia/Darwin

In [the IANA list](https://en.wikipedia.org/wiki/Time_in_Australia#IANA_time_zone_database), Darwin has an easy to remember name.

**Comment by jesus2099** [comment]
I don't find this anywhere else than in SUPER MIND:

- https://github.com/search?q=repo%3Ajesus2099%2Fkonami-command+getMilliseconds&type=code
- https://github.com/search?q=repo%3Ajesus2099%2Fkonami-command+getSeconds&type=code
- https://github.com/search?q=repo%3Ajesus2099%2Fkonami-command+getMinutes&type=code
- https://github.com/search?q=repo%3Ajesus2099%2Fkonami-command+getHours&type=code

https://github.com/jesus2099/konami-command/blob/ffd458d6e4d82c584df1bf20b859dc35e47cfdb2/mb_SUPER-MIND-CONTROL-II-X-TURBO.user.js#L1649
