### ISSUE TITLE
Few requests about mb. INLINE TRACK ARTIST

### ISSUE THREAD

**Issue by culinko** [jesus2099/konami-command#345]
Hello there :)

I've been using your mb userscripts for a really long time and I'm very grateful that you are still maintaining them. I've come across a question and two requests about this particular userscript I'd like to know. Here they are: 

- Whenever a recording contains disambiguation, the disambiguation part is highlighted. Is this intended? And if it is and you don't want to disable it, is there a way to turn it off by changing something in the script so I can disable this for myself locally?
- If a recording title doesn't match the track title, it's highlighted both on the release page and on the recording page. However if the AC doesn't match, it's highlighted only on the recording page and not on the release page. Do you think it would be possible to also highlight it on release page? The only question would be how to fit it in and also dealing with releases which don't have the Artist column (releases where all tracks match the release AC), in which case you could position the artist name near the rating column. This is my mockup how it could look like for both types of releases: http://imgur.com/a/ZQCeJ.
- I know this userscript is called "inline **track** artist", but since it also shows the title differences, I was wondering it could be expanded from medium/recording differences to release group/release differences as well. It could show differences for AC and titles on these 4 pages: release page. release group page, label page and artist's release page (such as https://musicbrainz.org/artist/78a2cf98-3fac-43f1-86b5-974bed8c89ca/releases).

Let me know what do you think about these ideas and also if you'd prefer me to split these into separate issues on github, I'll gladly do it. Thanks for any feedback, much appreciated!

**Comment by jesus2099** [comment]
Thanks very much for the ticket @culinko.
I think the features you tell are in two scripts.
I think I should probably merge them... ☺

**Comment by culinko** [comment]
Well, I am using both of the scripts, so you might be right about that :) However there might be people editing classical releases which have (as far as i remember) performers on recording and composers on track, so they might not like it bundled with the other script if they use the other one.

As for my first question, I still wonder, is the comment highlighting intentional?

**Comment by jesus2099** [comment]
I think I remember that there is highlighting whenever track title is different from recording title plus comment, indeed. And it was intentional.
Because it can show a possible mistake in some cases.
Like a non remix track linked to a remixed recording.

**Comment by culinko** [comment]
Hello again! I decided that I don't want to use the highlighting recording comments feature anymore. I still do want the comments to be shown, but in grey color and without the shadow. Because I won't use the feature anymore, I decided to remove the comment from the comparison string as well, so the script wouldn't need to use additional resources. In mb. INLINE STUFF, I changed so far (I don't have any previous experience with scripting btw. so everything I did was an intuition):

I changed row 267 to `var sameCompleteName = aRec.textContent == recnameNet[mbid].name;`
and row 287 to `if (markTrackRecNameDiff && recnameNet[mbid].comment) {`

If I am correct, this should remove the comment from the track/recording comparison and should display the comment whenever it exists. Interestingly enough, this doesn't change anything in the script's functionality so far, because if a recording has a comment, it's automatically different from the track name (so I don't know why do you need to compare it in the first place :P).

Now for the style part, I am still struggling to find out the cleanest solution possible. So far I got it working by changing the value `recdis` in row 289 to something like `recdis2` and then inserting a new row in position 88 which is something like `css.insertRule("span." + userjs + "recdis2 { color: #999}",1);`. I don't know how the original row works (for example I don't know what is the "a", the "span." the square brackets and why is the userjs called twice), but this method of adding the second `css.insertRule` feels kinda hacky to me. So I was wondering, is there any way to keep the original value `recdis` in row 289 and just modify the row 87 in a way that it keeps the grey shadow + maroon color for the `recname` value and then I define the `recdis` with no shadow and grey color? Or is it impossible to define two different color schemes in one `css.insertRule`?

I am sorry for spamming this ticket, I would message you on Discourse but private messages are still disabled there... Many thanks for your assistance!

**Comment by jesus2099** [comment]
It’s good to have this here instead of private. :)
Sorry I have no time nowadays but I think my goal was that a track called **A (sax version)** should not be considered different than either a recording called **A (sax version)** or a track called **A** with a **sax version** comment. This is why I use the comment in the comparison.

**Comment by culinko** [comment]
Oh, that scenario never occurred to me and is actually very clever!

Don't worry, I will try to find more info about `css.insertRule` or bother someone on irc about the color thingy :)

**Comment by jesus2099** [comment]
I can help you for the styling.
`insertRule` takes a string that should follow the same syntax as a cascading style sheet (`.css`) files.
Which one of the three opening post items is your style question?
What do you want to change to the styling, in a few words?
I guess it’s about how is styled a track that differs from current recording, right?

**Comment by culinko** [comment]
I want to change the **comment** highlight from maroon text color and grey shadow to grey text color and no shadow. I want to keep the recording highlights untouched.

**Comment by jesus2099** [comment]
You can go to the 87th row, indeed:

    			css.insertRule("a[" + userjs + "recname], span." + userjs + "recdis { text-shadow: 1px 2px 2px #999; color: maroon}", 0);

And replace it with:

    			css.insertRule("a[" + userjs + "recname], span." + userjs + "recdis { color: grey}", 0);

Maybe I should use this in the script.
Please use it for a while and tell me what you think…

Could you check boxes in your initial post when you consider subjects are closed?

**Comment by jesus2099** [comment]
Sorry I edited my code just above because I didn’t get quite your request yet.
Could you send me the link to the release you pictured so I can check?

**Comment by jesus2099** [comment]
Found it: https://musicbrainz.org/release/19950f6f-9c91-43d1-aa7b-dae2c05405b1

**Comment by jesus2099** [comment]
I will simply use the MBS’ grey `.comment` style class.
And it does work good with the case I described: [track name = recording name + " (" + recording comment + ")"](https://musicbrainz.org/track/ec741961-eb9e-4cfc-982a-7055d98a4be6).
This track has a `span.name-variation` by MBS because indeed track name ≠ recording name but my script does not mark it as different and does not display the comment in double.

**Comment by jesus2099** [comment]
FYI both script are already marked for merge in #129.

**Comment by culinko** [comment]
Yeah this was my initial thought, that I can't have two different color values in one `css.insertRule`. I was wondering if the index at the end should be 1 e.g. `css.insertRule("span." + userjs + "recdis { color: #999 }", 1);` but I see you dropped it for the `.comment` style class, which looks much cleaner. It looks exactly as I envisioned, hopefully other people won't crucify me for this change, because you changed it globally in your script so everyone who updates the script will have it this way.

There is one additional thing I was wondering about today, this time regarding the tooltip. In row 270, there is:
`ntit = (ntit ? ntit + " —\u00a0" : "") + "track name: " + aRec.textContent + "\r\n≠rec. name: " + recnameNet[mbid].name;` which looks like this:

![tooltip1](https://user-images.githubusercontent.com/11700272/29186739-aeb71d9e-7e0d-11e7-8c66-804aa79ed52f.png)

Can I ask why is the ntit value compared in `(ntit ? ntit + " —\u00a0" : "")` and why are the additional things (the title and dashes) displayed? I removed the mentioned part from the row so only `ntit = "track name: " + aRec.textContent + "\r\n≠rec. name: " + recnameNet[mbid].name;` would remain, which would look like this (imo much more clear): 

![tooltip2](https://user-images.githubusercontent.com/11700272/29187005-9432588e-7e0e-11e7-8cc4-43efe3affc9c.png)

So I am wondering, am I losing any functionality with this change?

**Comment by jesus2099** [comment]
Sorry I created a [discussion](https://community.metabrainz.org/t/display-more-info-with-mb-inline-stuff/320907) to keep GitHub tickets focused on single/simple tasks. :)

Could you please repost over there and we’ll create one ticket for each requests that will come out of the discussion, OK? :)

I am now renaming and closing this ticket to consider this single enhancement: [Use MBS disambiguation styling (comment)](https://github.com/jesus2099/konami-command/issues/345#issuecomment-321517491).
