### ISSUE TITLE
iTunes redesign 

### ISSUE THREAD

**Issue by 5moufl** [jesus2099/konami-command#353]
since the redesign I can’t click on the cover as i used to
if I can debug anything tell me what you need

**Comment by jesus2099** [comment]
Hi @5moufl can you give me a link, I’m lazy. :)

**Comment by 5moufl** [comment]
https://itunes.apple.com/us/album/songversation-medicine/id1250617342 for e.g. but it doesn’t work on any link

**Comment by jesus2099** [comment]
The biggest image I can now find for this one is https://is1-ssl.mzstatic.com/image/thumb/Music127/v4/df/a8/b2/dfa8b2b8-cf11-181c-f63e-dbd2f0bbe24b/source/939x0w.jpg …  :/ Strange.

**Comment by jesus2099** [comment]
I now have to delay the script to after iTuns page changes (font jump).
`setTimeout(…, 5000);` works but is even a bit too long.
I could restore the permalink on header but not yet the biggest cover art…

**Comment by 5moufl** [comment]
https://github.com/dufferzafar/Userscripts also links to 939px covers :/
`// @run-at document-idle` might be better than `setTimeout()`

**Comment by jesus2099** [comment]
Thanks for the link. As I don’t really use iTunes, as iTunes is fighting against user script and as there is another similar script, I think I will not maintain my iTunes script any more. 😅😌

**Comment by Mirgolth** [comment]
Could you give a link to the" another similar script" ?

**Comment by jesus2099** [comment]
It’s in [5moufl’s comment](https://github.com/jesus2099/konami-command/issues/353#issuecomment-326975323) (iTunes import or something). :)
Sorry I forgot.

**Comment by jesus2099** [comment]
@Mirgolth, There is also this [ Bookmarklet/userscript: Full-size cover art from last.fm, soundcloud, itunes and more ](https://community.metabrainz.org/t/bookmarklet-userscript-full-size-cover-art-from-last-fm-soundcloud-itunes-and-more/83968?u=jesus2099).
I don’t know if it still works or if broken like others.

**Comment by jesus2099** [comment]
I have removed this script now, it’s [history](https://github.com/jesus2099/konami-command/commits/master/itunes_FULL-SIZE-COVER-IMAGE-DOWNLOAD-LINK.user.js).
