### ISSUE TITLE
Doesn’t complete on large collection

### ISSUE THREAD

**Issue by cheezmo** [jesus2099/konami-command#354]
I first started noticing that Artists and Recordings were not being highlighted so tried reloading the entire collection (about 4600 releases) and noticed that it isn't actually completing.  Here is a screen shot showing the last messages...

I'm using the latest Safari on MacOS High Sierra (problem started while I was on Sierra).  I'm using TamperMonkey to load the script.

After release groups are saved, nothing else happens...
<img width="616" alt="screen shot 2017-10-05 at 1 14 10 pm" src="https://user-images.githubusercontent.com/10653785/31243205-22786372-a9cf-11e7-90c0-60b09c94a7ca.png">

**Comment by cheezmo** [comment]
Maybe a quota being exceeded?  
<img width="741" alt="screen shot 2017-10-05 at 1 18 58 pm" src="https://user-images.githubusercontent.com/10653785/31245399-d5ca8644-a9cf-11e7-8ea7-43f9d13624aa.png">

**Comment by cheezmo** [comment]
Used a website to check the quote in Safari...

<img width="509" alt="screen shot 2017-10-05 at 1 21 45 pm" src="https://user-images.githubusercontent.com/10653785/31245511-3600ea1c-a9d0-11e7-8f71-4647b213fd79.png">

**Comment by cheezmo** [comment]
Found this resource for testing limits, pretty clear the collection is too big for Safari's localstorage. 

According to this website an indexed DB could be used to store much more data...  Not sure what would be involved to change your scripts to use an alternative storage mechanism such as that.

https://demo.agektmr.com/storage/

**Comment by jesus2099** [comment]
OK I see.
Thanks very much for the ticket !

So you mean it stopped at 3855 of 4662 entries…
Then if RG load stops, no other entities are browser for storage.

My collection is smaller and legacy Opera presto already asked me long time ago to set a bigger localStorage.
Firefox also did OK.

---

- You’re only using Safari ? Never Firefox ?
- Can you tell me what options are supported by Safari when you go to your test page ?
  For me for instance, only WebSQL, localStorage and sessionStorage are not marked as « Not supported on this browser » 

---

I thought all browsers could get such (user allowed) unlimited storage…
Thanks for your search, I’ll have to have a look to that IndexedDB stuff.
But it is not supported by my browser so I’ll probably have a fall‐back system to localStorage (for me).

**Comment by jesus2099** [comment]
Compatibility table, thanks to https://demo.agektmr.com/storage/

Browser     | Quota | FileSystem | IndexedDB | WebSQL | localStorage | sessionStorage
----------- | ----- | ---------- |---------- | ------ | ------------ | --------------
Opera v12   | :x:   | :x:        | :x:       | :o:    | :o:          | :o:
Firefox v56 | :x:   | :x:        | :o:       | :x:    | :o:          | :o:
Safari v??  | : :   | : :        | : :       | : :    | : :          | : :

**Comment by jesus2099** [comment]
BTW common-def3fa9295.js seems to be a MusicBrainz script so maybe COLLECTION HIGHLIGHTER, by having saturated your `localStorage`, makes MB act wrong now so you may wish to remove COLLECTION HIGHLIGHTER data.

To do this you can either load a very small collection or install the [mb. LOCAL STORAGE MANAGER](https://github.com/jesus2099/konami-command/blob/master/mb_LOCAL-STORAGE-MANAGER.user.js) (click **Raw** button) to completely remove all items starting with `jesus2099userjs126380` (in the MB **About Us** top bar menu)

**Comment by jesus2099** [comment]
https://www.html5rocks.com/en/tutorials/offline/quota-research/ by same guy shows that your Safari localStorage might be limited to 5 Mb.

**Comment by jesus2099** [comment]
![image](https://user-images.githubusercontent.com/1401086/31272241-91ef26ee-aa8a-11e7-998f-896eff833a04.png)

Just for fun, I have now loaded your 4662 release collection after approx. 1h. :)

Key                                 | Size (characters)
----------------------------------- | -----------------:
jesus2099userjs126380artists        | 143,782
jesus2099userjs126380collections    | 37
jesus2099userjs126380labels         | 21,867
jesus2099userjs126380recordings     | 2,295,961
jesus2099userjs126380release-groups | 142,635
jesus2099userjs126380releases       | 172,494
jesus2099userjs126380works          | 810,004

It takes more than 2 Gb of recordings in local storage… :/

**Comment by cheezmo** [comment]
Safari (v11) supports indexedDB, WebSQL, localstorage, and seasonstorage.  Not quota or filesystem.

**Comment by cheezmo** [comment]
Actually isn't it more like 2.3Mb (not Gb!).  I think (from that page above, Safari's limit was around 2,600,000 characters so that is why I have just started hitting limits as my release groups + releases + artists + recordings would just start going over that limit.

**Comment by cheezmo** [comment]
Here is the site that tested the limit and came up with 2,600,000

https://arty.name/localstorage.html

**Comment by cheezmo** [comment]
Just read somewhere that the standard limit for webkit is 5Mb, but since they are using UTF-16 now, that effectively limits things to 2.5M characters.  All makes sense now I think.  Just need something that supports more storage for Safari.

**Comment by jesus2099** [comment]
Oh yes, MB not GB ! :)
Thanks for your details, @cheezmo.
We really do need this feature genuinely in MB site, though… With [MBS-3491](https://tickets.metabrainz.org/browse/MBS-3491) it would be slick, fast, no problems.

**Comment by cheezmo** [comment]
I'm thinking of trying to use the compress/decompress routines from this.  That would get me by for now.  Assume I just do it on every string being added or restored from localstorage.

https://labs.ft.com/2012/06/text-re-encoding-for-optimising-storage-capacity-in-the-browser/

**Comment by jesus2099** [comment]
Yes good idea, their option number two and no need for the snowman ⛄ trick, btw.

**Comment by jesus2099** [comment]
It will double the capacity.

**Comment by jesus2099** [comment]
And moreover they say indexed DB does not  necessarily have highest capacity than local storage…

**Comment by cheezmo** [comment]
I didn't feel like trying to write the decode routine for that one so I took a crack at using the LZString library to compress to UTF16.  I almost got it to work but I'm stuck debugging it.  I have some log data showing that I can compress it, save it, read it and decompress it.  But when i go to decompress it later I get a weird error deep inside the decompressUTF16 routine.  I'm attaching my almost working script, I just don't have the javascript debugging chops to figure it out...


[compressedcollections.js.zip](https://github.com/jesus2099/konami-command/files/1363814/compressedcollections.js.zip)

**Comment by cheezmo** [comment]
just realized the snowman guy's decompress script at the bottom was for the compress at the top not the lower one.  Got it working I think!

**Comment by cheezmo** [comment]
Here is my working script with compression in case you want to do anything with it.  Checked it on my big collection and it looks good!
[compressedcollections.js.zip](https://github.com/jesus2099/konami-command/files/1364147/compressedcollections.js.zip)

**Comment by jesus2099** [comment]
Thanks very much @cheezmo, I will check it out!

**Comment by jesus2099** [comment]
I will compare result sizes on your collection with your fix and with the other fix (the full ASCII method).
This decompression is not slowing down each MB page loading?

**Comment by cheezmo** [comment]
No noticeable performance issue.

**Comment by jesus2099** [comment]
OK, with your compression, size taken by entities in `localStorage` is only half now.
I hope it will be enough until MBS-3491.
If not, I will need lha compress or something. :)
Thanks very much, @cheezmo.

**Comment by jesus2099** [comment]
@cheezmo, BTW, maybe [GM_setValue](https://github.com/jesus2099/konami-command/issues/333#issuecomment-305930021) has no size limitation?

**Comment by jesus2099** [comment]
@cheezmo, could you please try to:

1. [Clean up your local storage](https://github.com/jesus2099/konami-command/issues/354#issuecomment-334687056)
2. Uninstall COLLECTION HIGHLIGHTER
3. Install this alternative version https://github.com/jesus2099/konami-command/blob/try-GM_setValue/mb_COLLECTION-HIGHLIGHTER.user.js
4. Load your huge collection (be patient)

And then tell me if it works?
It would be super great of you! :)

**Comment by jesus2099** [comment]
This solution is great, it stores data in a `mb._COLLECTION_HIGHLIGHTER.db` file on hard drive so it may be almost unlimited!

**Comment by cheezmo** [comment]
Thumbs up from me.  Worked great.

**Comment by jesus2099** [comment]
Thanks @cheezmo for this kick in the ass of my script!

**Comment by cheezmo** [comment]
Your script now goes to 11.
