### ISSUE TITLE
OUJS Fix

### ISSUE THREAD

**Issue by Martii** [jesus2099/konami-command#358]
Hey mate,

OUJS has made a change recently to require SPDX codes for OSI approved licensing.

In order to improve the appearance of your script homepages it would be appreciated if you could modify all of your affected scripts *(and you have a bunch)*.

Currently you utilize a Content License of `CC BY-NC-SA 3.0 (https://creativecommons.org/licenses/by-nc-sa/3.0/)`... however the server will reject your further updates and new scripts until you do two things.

1. Declare a Code License... perhaps `// @license MIT` since it's the least restrictive/permissive.
2. Change your soon to be visually dual-licensed CC to `CC-BY-NC-SA-3.0; https://creativecommons.org/licenses/by-nc-sa/3.0/legalcode`. The TOS already specifies that it's already dual licensed but we worked out the visual aspects and some validations.

So assuming you pick `MIT` for your Code License it would be like this in your metadata block

``` js
// @license CC-BY-NC-SA-3.0; https://creativecommons.org/licenses/by-nc-sa/3.0/legalcode
// @license MIT
```

Note the last `@license` is primary and that's where the validation comes in. If it detects Content License the server will reject it there. `@license` is a FILO list if that helps with terminology.

Within about a week of this migration we plan on toggling the enforcement for including a Code License from the TOS for unlicensed arbitration administration.

Thanks for a moment of your time and your understanding,
OUJS Admin *(Staff too)*

**Comment by jesus2099** [comment]
Thanks very much that each time you come and tell me! that’s very nice! :)
So I have some homework…
SPDX: https://en.wikipedia.org/wiki/Software_Package_Data_Exchange / https://spdx.org/learn
OSI: https://en.wikipedia.org/wiki/OSI_model

- You mean a Content licence is not something that should be used for programming and that I should use a more programming oriented licence, like MIT?
- Do I really have to use `@license` (American English, I never know which is **s** and which is **c**) or do you still support `@licence` (like in GB English and French)?

No more question, thanks to your big comment, I will do my homework ASAP, thanks again for your detailed notification. :)

**Comment by Martii** [comment]
> You mean a Content licence is not something that should be used for programming and that I should use a more programming oriented licence, like MIT?

Content is like a book with text and pictures and it's usually not FOSS Code in the strict word sense.... it's a fine line between the terminology. Basically dual-licensing covers you both on the FOSS side as well as the non-FOSS side. I utilize `CC-BY-NC-SA-4.0` *(Content Licence)* along with `GPL-3.0+` *(Code Licence)*... so both bases are covered. If you look for the word "Code" in CC you shouldn't be able to find it... they describe "works" usually which expands beyond computer code.

> Do I really have to use `@license`

You can use `@licence` if you wish... we transform it to `en-US` inside the system... but your code still shows `@licence`. :smile_cat:

> Thanks very much that each time you come and tell me! that’s very nice! :)

Not a problem. :smile:. I enjoy seeing your activity and chatting with you when something arises.

More reading for you:
* https://openuserjs.org/announcements/Licensing_enforcement
* The `@license` key accordian at https://openuserjs.org/user/add/scripts#userscript-block

**Comment by jesus2099** [comment]
Another question @Martii, https://creativecommons.org/licenses/by-nc-sa/4.0/ is more user friendly, do I **have** to link to https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode instead?

**Comment by Martii** [comment]
That can't be primary because it is a Content license only and not Code license... the dual licensed example at https://openuserjs.org/user/add/scripts#user-block-license shows how it's done with a sample Code license as primary and Content as secondary. All the current Code license SPDX's are listed at https://openuserjs.org/user/add/scripts/new

> do I have to link to https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode

Not necessarily... we will autolink the SPDX codes for you. If a license needs additional, and allowable, restrictions is why the url is available.... however not every license allows restrictions like GPL. If you want to point it to your GH LICENSE file you may for script identification purposes in case someone tries to borrow your script and claim it is theirs. Most are too lazy or inexperienced to change all of the bread crumbs.

**Comment by jesus2099** [comment]
Thank you. :)
