### ISSUE TITLE
Crashes in Firefox v57.0.2 and/or Greasemonkey v4

### ISSUE THREAD

**Issue by Alfge** [jesus2099/konami-command#369]
with Firefox 57.02 mb.Inline Stuff doesn't show the acoustid nor the CAA count.
Example: https://musicbrainz.org/release/55bc8fa5-e435-4c82-88a9-1e60a4003598

Please take a look.

**Comment by jesus2099** [comment]
I have just installed FF 57.0.2 and confirm this script does not work on it.
I don’t understand yet the error messages over there (bad URL or something) but some other scripts do work, that’s the strange part…
Thanks for the issue report!

**Comment by Alfge** [comment]
Yes, some of your scripts are working with Firefox 57.0.2 and Greasemonkey 4.0 like mb. FUNKEY ILLUSTRATED RECORDS or mb. SUPER MIND CONTROL Ⅱ X TURBO. Other scripts I use from you, I didn't have tested yet.

**Comment by jesus2099** [comment]
My FF v57 randomly takes ages to load any MB page:

> Performing a TLS handshake with staticbrainz.org
> Performing a TLS handshake with musicbrainz.org

**Comment by jesus2099** [comment]
Ach.
I am rather stuck here as my work PC can run Firefox v57 is faces [a bug](https://support.mozilla.org/questions/1177372) that makes loading MB pages impossible.
My Home PC [cannot run Firefox v57](https://support.mozilla.org/en-US/kb/end-support-windows-xp-and-vista) at all.
:/

**Comment by Alfge** [comment]
FF v57 is on my Computer/Network very fast on all the MB-pages I opened till now, faster than FF 56.

**Comment by jesus2099** [comment]
mb_INLINE-STUFF does not seem to be using [the broken features of Greasemonkey 4](https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html) but [maybe you can try using Violentmonkey](https://www.greasespot.net/2017/09/greasemonkey-4-for-users.html).

**Comment by Alfge** [comment]
Thank you for your idea to use Violentmonkey. Now I use for all scripts with Violentmonkey. So far no problems :-)
Using:
mb. Inline Stuff
mb. Super Mind Control IIX Turbo
mb. Mass Merge Recordings
mb. Plain Text Tracklist
mb. Funkey Illustrades Records
mb. Auto-Focus + Keyboard-Select
Import Discogs releases to MusicBrainz

**Comment by jesus2099** [comment]
I hope you will like Violentmonkey as much as you like Greasemonkey.
I feel not good making you change habits like this…
I keep this ticket open for the day when my work network works better!

**Comment by jesus2099** [comment]
Actually, so it seems that there is at least that Greasemonkey v4 bug #372.

**Comment by Martii** [comment]
Glad this wasn't just me... [mutual found workaround](https://github.com/Martii/UserScripts/commit/28b14e5e7129085a07f80e9c2c7bb24f0c48d5d1). Thanks for the follow up. :)

**Comment by jesus2099** [comment]
@Alfge, I have tested today with Firefox 63.0.1, Greasemonkey 4.3 and INLINE STUFF 2017.8.10 and it works!
I can close this ticket.

**Comment by jesus2099** [comment]
I have now updated everything and it also works (CAA count and AcoustIDs) with latest versions: Firefox 63.0.3, Greasemonkey 4.7 and INLINE STUFF 2018.3.12. :) :+1:

**Comment by jesus2099** [comment]
Just for the record, the two issues mentionned by the OP are now fixed with Greasemonkey 4.11:

https://musicbrainz.org/release/bf7a0c44-c815-4459-a819-106f188e52d2

- _Cover Art (0)_ is detected ✔️ and turned into yellow **Add Cover Art** ✔️ 
- 22 AcoustIDs are displayed ✔️
