### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by thienha1** [jesus2099/konami-command#374]
Can you make scripts that disable/confirm OK on dialogs?!
Here:::
https://upanhtocdo.com/image/Fas5s

**Comment by jesus2099** [comment]
Hello.
On what site?
Please provide example url.

**Comment by thienha1** [comment]
First go https://www.earnstations.com/
> login here: h.a.t.h.ien6.9@gmail.com
Pass: 123456
After, click watch then click something video and see the problem

**Comment by jesus2099** [comment]
Sorry but I am not really into this kind of site that promise to earn « millions in cash. »
I only have *very limited* free time so I prefer to spend it on sites that I have some interests in.

**Comment by jesus2099** [comment]
Please remove your email address, login and password as long as you can edit your post, it is not very safe.
