### ISSUE TITLE
CTRL+ENTER does no longer submits!

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#388]
Extracting this bug from #386, I must find what script does this feature…

**Comment by jesus2099** [comment]
It works in edit history pages but not in release editor nor in merge pages.

**Comment by jesus2099** [comment]
OK found it’s CONTROL_ENTER_SUBMIT, part of SUPER SCRIPT, so it’s maybe same bug as #386, eventually.

**Comment by jesus2099** [comment]
Doesn’t work in edit-cover-art either any more.

**Comment by MajorLurker** [comment]
Glad you already noticed this, just seemed to have happen recently.

**Comment by jesus2099** [comment]
Same problem for DOUBLE_CLICK_SUBMIT on https://musicbrainz.org/cdtoc/attach?toc=1+11+264760+187+26997+57622+79060+101885+134085+169847+187235+207472+239447+254735&filter-artist.query=jimmy+smith
I think it’s all because of #386 because here again I see the dreaded `TypeError: Cannot read property 'toUpperCase' of undefined` error in the console. :/

**Comment by jesus2099** [comment]
It’s because of #386.

**Comment by jesus2099** [comment]
Oh, double clicking labels does not work any more!
