### ISSUE TITLE
Double-click selecting headers with UNLINK_ENTITY_HEADER duplicates first word at the end

### ISSUE THREAD

**Issue by Freso** [jesus2099/konami-command#41]
E.g., double-click selecting and copying the title of https://musicbrainz.org/work/1864dbe8-4941-4c87-93d7-806c0a2da34f will result in "Bright Cecilia: Variations on a Theme by PurcellBright".

**Comment by jesus2099** [comment]
It doesn’t happen in Opera so I haven’t spotted that.
Is it with Firefox or Chrome ?

**Comment by Freso** [comment]
Firefox. It seems to generate this markup, and I'm guessing it's happening because of no space between the two `<bdi>`s (from https://musicbrainz.org/work/292e16bc-8c81-4875-9456-aefc36ed1387):

    <h1><a><bdi>Into the Everlasting, op. 9</bdi></a><a style="position: absolute; left: -1000px;" href="https://beta.musicbrainz.org/work/292e16bc-8c81-4875-9456-aefc36ed1387"><bdi>Into the Everlasting, op. 9</bdi></a></h1>

**Comment by jesus2099** [comment]
Thank you for the details, I will check it out. :)
`<bdi>` is an **inline** tag… I guess double‐click will select the content of the nearest parent **block** container (`<h1>` here) anyway. Which makes why it works in Opera kind of a surprise. ;)

**Comment by jesus2099** [comment]
I have took the drastic solution of removing the link but it’s only done when your mouse gets close to that thing, so any other user scripts should already have been able to use that before it’s gone. :)
