### ISSUE TITLE
AC no longer show

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#415]
Probably also linked to recent [MBS move of many things to “React”](https://blog.musicbrainz.org/?p=7231) change, like #414.

**Comment by jesus2099** [comment]
Ah, it seems that `/ws/2/recording?query=rid:<MBID>` no longer shows artist credits at all for tracks.

**Comment by jesus2099** [comment]
I don’t remember why but, on the other hand, `/ws/2/recording/<MBID>?inc=releases+artist-credits+mediums` has never yet provided the information needed for this script.

**Comment by jesus2099** [comment]
https://musicbrainz.org/recording/387ede5a-2740-46a4-ba94-01f686dcf015

**Comment by jesus2099** [comment]
Fixed by getting recording data from `/ws/2/recording/<mbid>` lookup instead of
from `/ws/2/recording?query=rid:<mbid>` search (which has lost AC data).

**Comment by culinko** [comment]
There was an AC issue on MB side so maybe this is relevant? https://github.com/metabrainz/sir/pull/99
