### ISSUE TITLE
Upvoted tags are not seen if not new. Downvoted tags are still seen if not removed.

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#419]
Seen with [any of the others tags or genres](https://musicbrainz.org/artist/5441c29d-3602-4898-b1a1-b77fa23b8e50/details).

---

- I added `tag1, 2, 3` they were all 3 ownified. :green_circle:  
- If I upvote existing tag, it is not ownified. :negative_squared_cross_mark: 
- I add `british, 1, 2, 3` (where british is existing), only 1, 2 and 3 are ownified. :negative_squared_cross_mark: 
- I downvote `british` (after having upvoted it and reload page), it remains ownified. :negative_squared_cross_mark:

**Comment by jesus2099** [comment]
It’s because I only scan for `DOMNodeInserted` event, I should also intercept `DOMAttributeModified` or something like that, if such thing exists.

**Comment by jesus2099** [comment]
- I added `tag1, 2, 3` they were all 3 ownified (now without change). :+1: 
- If I upvote existing tag, it is not ownified. :-1: 
- I add `british, 1, 2, 3` (where british is existing), only 1, 2 and 3 are ownified. :-1: 
- I downvote `british` (after having upvoted it and reload page), it remains ownified. :-1:

**Comment by kellnerd** [comment]
> I downvote `british` (after having upvoted it and reload page), it remains ownified. 👎

Should this already have been solved by https://github.com/jesus2099/konami-command/commit/4fa74ddc55ec51927562f6e9d7215e2b43b1120b? Currently I can not upvote/downvote/withdraw any tag in Firefox 83.0 with TAG_TOOLS (from version 2020.11.27) enabled. It seems that the MBS code is somehow blocked by the userscript because even after a page reload the tag sidebar has not changed.

**Comment by jesus2099** [comment]
Oh yes, I will try.
I think I know why this bug, I had to stop the event propagation for some reason but it seems I find another way to avoid that.
Thanks very much, @kellnerd!

**Comment by jesus2099** [comment]
Hmm, I checked 4fa74ddc55ec51927562f6e9d7215e2b43b1120b, there is no kind of `stop()`.
I will debug as soon as possible.

**Comment by jesus2099** [comment]
I found, it's my small text, inserted at the last minute in my script, after all my tests, between MBS’ React (I suppose) JavaScript and its handled HTML.
I moved it away and it is not blocked any more.

**Comment by jesus2099** [comment]
That's it @kellnerd, tell me if it works or not, now. Thanks.

**Comment by kellnerd** [comment]
Thank you for the quick fix, it is working again 👍

**Comment by jesus2099** [comment]
Thanks for the confirm!
