### ISSUE TITLE
AUTO-FOCUS + KEYBOARD-SELECT: experimental tracklist up/down feature broken

### ISSUE THREAD

**Issue by uklauer** [jesus2099/konami-command#42]
Going up/down from a track name etc. to the one above/below with the cursor keys doesn’t work. I could fix it by changing the selector on line 174 to `div#tracklist` (from `div.advanced-tracklist`), so there may have been a server change.

**Comment by jesus2099** [comment]
Thanks very much, Chirlu ! :)
