### ISSUE TITLE
Script broken :  ERROR: Execution of script 'mb. MASS MERGE RECORDINGS' failed! Cannot read property 'textContent' of null(program):666 (anonymous function)

### ISSUE THREAD

**Issue by Xrampino** [jesus2099/konami-command#43]
I got this error today when going to this page :

http://musicbrainz.org/release/cf8886a0-cb2b-41ec-841f-894561723229

**Comment by jesus2099** [comment]
Unfortunately, MASS MERGE is not supposed to work since a certain MB server update (#29).
I don’t have the same error **666** (the number of the beast) as you but it doesn’t work for me either anyway.
Sorry I’ll try to repair as soon as I find some free time… :)
