### ISSUE TITLE
 mb. INLINE STUFF doesn't work on beta.mb

### ISSUE THREAD

**Issue by Lotheric** [jesus2099/konami-command#445]
I edited the script to use it (replaced test with beta since I don't use the test server).
It works in Opera + Tampermonkey btw (if you want to add it to your script)

- Lotheric

**Comment by jesus2099** [comment]
Oh yes sorry, this regression came recently with a95549c6b5ba345945dd91ae21c22deff7f2212e

**Comment by Lotheric** [comment]
It's not working again, another regression?

**Comment by jesus2099** [comment]
Thanks @Lotheric.
This time it's not a regression. 😅
