### ISSUE TITLE
Within minc, script now only runs in album page

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#463]
> @dragonzeron:
> It seems that the website has added nextone ids to the side of the works and because of that your addon does not show up on minc only on the album pages so if you can maybe edit the addon that would be great
> it still works if there are multiple works on the same page but only if there is more then 2 otherwise it doesn't work

**Comment by dragonzeron** [comment]
about how long will it take to get a new version up and running

**Comment by jesus2099** [comment]
I can't say. Next time I need to browse over there.
Please give one example link because I don't really get it what is broken.

**Comment by dragonzeron** [comment]
![Minc](https://user-images.githubusercontent.com/35818927/66434217-aff07780-e9e7-11e9-9ca6-2ab2c40d2b24.JPG)
Basically since October 3rd Minc has added nextone ids to the top of the page as seen on this screengrab and therefor where the old musicbrainz work adds was for the jasrac its no longer there because of it so I think if you can you could place the addon down on the page if that is how coding works to have it fit the new format

**Comment by jesus2099** [comment]
This is https://www.minc.gr.jp/db/SakCdInfo.aspx?SAKUHINCD=09243844 but what did you use to find in those work pages? What do you mean by _it still works if there are **multiple works on the same page**_? Can you give me the link of a page that works?

**Comment by dragonzeron** [comment]
but because of some works not having any recent releases on cds I cant be able to add them to the database

**Comment by jesus2099** [comment]
This was [this is life work search](https://www.minc.gr.jp/db/SakCdInfo.aspx?GTITLE=this%20is%20life&SAKUSINM=&ARTNAME=&DATATYPE=2&SRCHTYPE=1).

**Comment by dragonzeron** [comment]
Yeah and it shows the add on for the musicbrainz but when you go the specific page it doesnt show up anymore

**Comment by dragonzeron** [comment]
if you look up the work 駆けろ!スパイダーマン it doesnt show the mb add and also the nextone ids should be added to the thing 
![minc 3](https://user-images.githubusercontent.com/35818927/66516940-cd851600-eaa7-11e9-8a86-e2939a465118.JPG)

**Comment by jesus2099** [comment]
You know, I don't fully understand what you say.
what is nextone id? What is mb add on?

Could you post a URL (not a screenshot) and say what is missing in this page?

**One URL : What is missing.**

**Comment by dragonzeron** [comment]
https://www.minc.gr.jp/db/index.html I dont know how to link works but yes the yellow m link is missing

**Comment by dragonzeron** [comment]
so did you see the missing yellow link

**Comment by jesus2099** [comment]
Yes, I have seen it and started working on it Friday. I will probably fix it soon. 😁

**Comment by dragonzeron** [comment]
any date for release

**Comment by jesus2099** [comment]
I had no time since that day, yet.
I can't tell when I have time.
It doesn't seem like a long fix but I don't have much time free.

**Comment by dragonzeron** [comment]
dang it ok

**Comment by jesus2099** [comment]
[This album page](https://www.minc.gr.jp/db/AlbInfo.aspx?CAT1=TEDA&CAT2=10592) does not show any work links (I think it's supposed to).

**Comment by dragonzeron** [comment]
it shows it for me

**Comment by jesus2099** [comment]
![Screenshot_2019-10-24-17-16-49-434_org mozilla firefox](https://user-images.githubusercontent.com/1401086/67499985-44163c00-f682-11e9-940a-c79f2b275547.png)
Oh yes indeed I see it in Firefox for Android!
OK so it just means that my ongoing fix for this ticket is breaking this page on my active browser, Vivaldi on Windows 10.
Thank you Mr. Dragon.

**Comment by dragonzeron** [comment]
your welcome

**Comment by dragonzeron** [comment]
Do you think this update will go live this week or are you still working on it

**Comment by dragonzeron** [comment]
any update

**Comment by jesus2099** [comment]
I am now making the fix.
I think it works in all pages but tell me, once you update the script to version 2020.6.26, if anything of this kind is still broken on minc.

**Comment by dragonzeron** [comment]
I still cant add the artist or publishers still

**Comment by jesus2099** [comment]
No, indeed.
But that's another issue: #499.
