### ISSUE TITLE
Tracks are missing leading zeros for minutes

### ISSUE THREAD

**Issue by culinko** [jesus2099/konami-command#474]
**Script:** INLINE TRACK ARTIST

Today I found out that the leading zeros for minutes are missing. As you can see on this example recording: https://musicbrainz.org/recording/240a50d5-aaf4-402f-9813-eb43ae83023f , the duration should be 1:09:28 but it's shown as 1:9:28 in both the Length column as well as on the sidebar on the right. Attaching screenshot below as well:

![minutes_leading_zeros](https://user-images.githubusercontent.com/11700272/68821710-4f5ff480-068f-11ea-9930-bb81eaaa07b5.png)

It might be related to the fix for #444 (or not).

Thanks for the fix :)

**Comment by jesus2099** [comment]
I will see that, thanks! :)

**Comment by jesus2099** [comment]
it's fixed now.
Please wait for version `2021.2.11`. :)
