### ISSUE TITLE
USER_STATS updates

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#475]
Edits section
========

Ranked total
--------------

I should move my link to the new [Total applied](https://musicbrainz.org/statistics/editors) and remove my Ranked total, made obsolete by it (same value).

Votes section
=========

The votes section is broken and should be repaired because there is no equivalent to my Ranked total there yet.

Ranked total
--------------

Good news is that now the vote search equals the editors statistics.
But it would a strain on MBS to compute it through this search.

Still mysterious that I cannot compute Ranked total by any combination of displayed Yes, No, Approve votes.

Vote | Count
-----|-------
_Yes_ | <del>_108 716_</del> <ins>but actually [107 246](https://musicbrainz.org/search/edits?auto_edit_filter=&combinator=and&conditions.1.args=1&conditions.1.field=voter&conditions.1.name=jesus2099&conditions.1.operator=%3D&conditions.1.voter_id=285909&field=Please+choose+a+condition&negation=0&order=desc&page=4290)</ins>
_No_ | <del>_4 320_</del> <ins>but actually [3 326](https://musicbrainz.org/search/edits?auto_edit_filter=&combinator=and&conditions.1.args=0&conditions.1.field=voter&conditions.1.name=jesus2099&conditions.1.operator=%3D&conditions.1.voter_id=285909&field=Please+choose+a+condition&negation=0&order=desc&page=134)</ins>
_Abstain_ | <del>_28 063_</del> <ins>but actually [26 797](https://musicbrainz.org/search/edits?auto_edit_filter=&combinator=and&conditions.0.args=-1&conditions.0.field=voter&conditions.0.name=jesus2099&conditions.0.operator=%3D&conditions.0.voter_id=285909&field=Please+choose+a+condition&negation=0&order=desc&page=1072)</ins>
_Approve_ | _466_ [**correct**](https://musicbrainz.org/search/edits?auto_edit_filter=&combinator=and&conditions.1.args=2&conditions.1.field=voter&conditions.1.name=jesus2099&conditions.1.operator=%3D&conditions.1.voter_id=285909&field=Please+choose+a+condition&negation=0&order=desc&page=19)
**Ranked total** | [111 038](https://musicbrainz.org/search/edits?auto_edit_filter=&combinator=and&conditions.1.args=2&conditions.1.args=1&conditions.1.args=0&conditions.1.field=voter&conditions.1.name=jesus2099&conditions.1.operator=%3D&conditions.1.voter_id=285909&field=Please+choose+a+condition&negation=0&order=desc&page=4442) **matches [editors statistics](https://musicbrainz.org/statistics/editors) and equals Yes + No + Approve (edit search counts)**
_Total_ | _141 565_ equals the sum of displayed Yes + No + Abstain + Approve

- Are some edits disappearing, thus the edit search inferior to displayed counts?
- Are displayed counts wrong?

Related to #383 and https://tickets.metabrainz.org/browse/MBS-9651

**Comment by jesus2099** [comment]
Linked to https://tickets.metabrainz.org/browse/MBS-10204 and https://github.com/metabrainz/musicbrainz-server/pull/1094.

**Comment by jesus2099** [comment]
Thanks very much for your great fix, @ErikLevin. :smiley:

**Comment by ErikLevin** [comment]
> Thanks very much for your great fix, @ErikLevin. 😃

Glad to help, thanks for your great scripts :)
