### ISSUE TITLE
Collapse release country list in RELEASE_EVENT_COLUMN

### ISSUE THREAD

**Issue by Lotheric** [jesus2099/konami-command#482]
https://tickets.metabrainz.org/browse/MBS-10424
reosarevok: Lotheric: why would it collapse countries where there are none?
Lotheric: reosarevok: ah! my bad. it's a column added by a jesus2099 script
Lotheric: you are right
Lotheric: => mb. SUPER MIND CONTROL Ⅱ X TURBO
Lotheric: The feature called: RELEASE_EVENT_COLUMN ☑ Displays release dates in label relationships page
Lotheric: I'll ask jesus :)

The MB collapsing is currently on beta :)

**Comment by jesus2099** [comment]
Above unrelated 2b1520ad6510dfcb5b650ce9cc4291e503420bb2 referred to #492, not this #482.

**Comment by jesus2099** [comment]
Thanks @Lotheric for the report.
Now it's done.
