### ISSUE TITLE
Cancelling a merge with "Merge helpor 2" shouldn't trigger the "destructive edit" alert

### ISSUE THREAD

**Issue by loujine** [jesus2099/konami-command#495]
Because of this, I had to write a fake edit note in order to be able to cancel a release merge, which is a bit annoying

I didn't explore further but I guess using event.explicitOriginalTarget to access the value (cancel) or class (negative) and not triggering stop(event) would work

**Comment by jesus2099** [comment]
BTW the problem with this specific cancel button use that it throws you at the MusicBrainz.org homepage. \*
So I never use it.

It's why I didn't see this bug, thank you, @loujine!

---

\* This is why I often leave the selected entities for merge living their life at the currently selected for merge mini form at the bottom of every page and eventually use one of three following methods:

- merging another entity type will ignore and remove those previous selected entities
- the clear queue and merge selected button, also added by this script
- or, if I'm really fed up seeing them in the bottom of every page merge mini form, the cancel button of that mini form is made instantaneous by this same script
