### ISSUE TITLE
Most highlights broken in merge page caused by recent React redraw

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#517]
Once AcoustIDs are loaded, it seems that React does not only redraw the AcoustID cells but also all the other cells `<td>` (Name, Artist, ISRCs, Length) of the table raw.
Which breaks any user script applied to them.

https://github.com/metabrainz/musicbrainz-server/pull/1586

https://github.com/metabrainz/musicbrainz-server/commit/2a3ce5f808fb907e78b3b565867a0a3b6859c974#diff-b9a383135673174ada27c6a8899eba55R506-R556

Apparently, the `<tr>` raw itself is not touched.

**Comment by jesus2099** [comment]
I could either put a daemon that re-highlights every x seconds or retry to go to style sheet approach (limited CSS mode #255).

**Comment by jesus2099** [comment]
Or I can check every so and then to wait that there is no longer any `p.loading-message` in the merge page to add my highlights.

**Comment by loujine** [comment]
> Once AcoustIDs are loaded, it seems that React does not only redraw the AcoustID cells but also all the other cells <td>
> the <tr> row itself is not touched.
Well I didn't expect that

> Is there a way to limit React redraws to only AcoustIDs cells?
I have to check, it couldn't work before but bitmap refactored the code so it might be possible now.

Note that the next idea was to add AcousticBrainz data (MBS-9487) in the same table, that's why having 'hydrate' on the whole table made the most sense

**Comment by loujine** [comment]
Didn't have time to test yet, I have to reinstall a local server.

> wait that there is no longer any p.loading-message

That sounds like a good idea since future columns for ABrainz would use the same message

**Comment by jesus2099** [comment]
mb_MERGE-HELPOR-2 ticket is #518.

**Comment by jesus2099** [comment]
I installed [React Developer Tools](https://github.com/facebook/react/tree/master/packages/react-devtools), but it doesn't really help. I see a bunch of non-hierarchical nodes without ID, without anything to browse in a clever way.

I don't see anything else yet than this non-react-sounding `p.loading-message` to tell me there is some deferred react stuff ongoing in a page.

I will wait a little more.

**Comment by jesus2099** [comment]
Here is the more clever diff: https://github.com/jesus2099/konami-command/commit/caec1d67b437cb8c091efa3dbf1d49c2d08361a7?w=1#diff-10123e8ab784193c4228772775fe026a6dbacc86eee152840eae52cd592e77ca
