### ISSUE TITLE
Provide user settings (big/small pics on/off)

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#520]
[Requested](https://community.metabrainz.org/t/display-cover-arts-in-musicbrainz-pages-mb-funkey-illustrated-records/180558/13?u=jesus2099) by @aerozol.

**Comment by jesus2099** [comment]
I made a quick test in Violentmonkey, but there is [a problem with Tampermonkey](https://github.com/Tampermonkey/tampermonkey/issues/2182).

**Comment by jesus2099** [comment]
Maybe I should try with something else than `GM_getValues` because:

Tampermonkey 5.3.0 MV3 does support `GM_getValues` but doesn't work in Kiwi Browser.

And Tampermonkey Legacy 5.1.1 MV3 does work in Kiwi Browser but doesn't support `GM_getValues`.

**Comment by jesus2099** [comment]
Hi @Aerozol,
I have added the settings, and they are not forgotten when userscript is updated.
You can find BIG PICS and SMALL PICS toggle menu items in userscript engine menu (monkey menu).

**Comment by Aerozol** [comment]
Amazing, thank you jesus2099!!
