### ISSUE TITLE
The "Change targets to remote/local" button is not always consistent with recording merge directions buttons

### ISSUE THREAD

**Issue by loujine** [jesus2099/konami-command#529]
Very low-priority minor annoyance: with the mass merge script, when I merge large boxsets medium after medium, the buttons are in an inconsistent state:

When I merge the first medium I choose to merge to local (so the button displays "Change all merge targets to remote") and all individual merge arrows show green ◀ (normal behavior).
When I reload the remote URL for the second medium:
- "Change all merge targets to remote" is still visible
- but individual arrows were reset to "▶"

So I need to click twice on "Change all targets to..." in order to get the right ◀ individual buttons

**Comment by jesus2099** [comment]
No need to _fix_ that.
