### ISSUE TITLE
"Time Parser" doesn't detect the times anymore

### ISSUE THREAD

**Issue by PeterCodar** [jesus2099/konami-command#534]
If you try to paste such a time listing for 
https://musicbrainz.org/release/a361d95c-f2ce-45fe-8240-49d5b9796072/

```
1. Ignir - Captaine Roshi (01:55)
2. Molotov - Captaine Roshi (03:21)
3. Appel - Captaine Roshi (03:11)
4. Détail (Feat Alpha Wann) - Captaine Roshi (03:02)
5. Interlude - Captaine Roshi (01:25)
6. Pigalle - Captaine Roshi (03:22)
7. Maintenant - Captaine Roshi (03:19)
8. Ébélé (Feat Gradur) - Captaine Roshi (02:53)
9. Champions - Captaine Roshi (02:57)
10. Déjà Fait (Feat PLK) - Captaine Roshi (03:01)
11. Pimpom - Captaine Roshi (02:59)
12. Mirage - Captaine Roshi (03:25)
13. Attaque II - Captaine Roshi (04:02)
14. Bouteille à La Mer - Captaine Roshi (02:35)
15. La Cabine - Captaine Roshi (02:29)
```
You get this "21 to 15" error message:

![Attaque II - Edit Release](https://user-images.githubusercontent.com/18629146/100546616-9f8e0280-3262-11eb-8cd1-49471de4f00d.png)

This behaviour is new since several days - maybe a server side change?
**What would currently be the best track listing for the time parser?**

**Comment by jesus2099** [comment]
Thanks for the report, @PeterCodar.
I have just changed the track length parser, indeed. :/

https://github.com/jesus2099/konami-command/commit/55e790e6997868ec417c33ead58cfea991c15f3b

**Comment by jesus2099** [comment]
Thanks to you I could fix this regression quickly!

**Comment by PeterCodar** [comment]
Thank you for the incredibly fast solution!
