### ISSUE TITLE
MASS MERGE displays HTML entities for remote track names

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#54]
[`&quot;`](https://musicbrainz.org/release/2177811e-03db-4242-bd20-6488a1f70c72)

**Comment by pankkake** [comment]
This was an old bug I think, and you can also find it in SPOT_AC

If you want I can create a bug report next time I encounter it

**Comment by jesus2099** [comment]
I don’t think this bug could have been there before MBS-3841…

If this bug ever was, it could have been before the use of that [`MB.Release.init(JSONRelease)`](http://web.archive.org/web/20141120165014/https://musicbrainz.org/release/00359158-0923-42ac-a559-f9367d88c962) explained in #55, where ampersand is coded `\u0026` (unicode notation) which renders well as & in Javascript. :)

:point_right: **Yes** please tell me if you see that bug in another piece, but SPOT_AC is only some styling, you must confuse with something else, no ?

    span.name-variation { border-bottom: 2px dashed maroon; }

**Comment by jesus2099** [comment]
For my record, I have checked **MERGE HELPOR 2**, **INLINE STUFF** and **INLINE TRACK ARTIST**, they are apparently free of this kind of bug.

**Comment by pankkake** [comment]
Example: http://imgur.com/2O96Hdw
Release: https://musicbrainz.org/release/c4cfb95a-9c98-424b-8c3d-d1caf56bb8a0

I think I've only seen it happen with &, but it might be other characters too.

**Comment by jesus2099** [comment]
Oh ! that. It doesn’t seem because a any user script. :)
That looks like [MBS-5993](http://tickets.musicbrainz.org/browse/MBS-5993) but for release editor.
