### ISSUE TITLE
Crash on releases where tracks have same ISRC/AcoustID

### ISSUE THREAD

**Issue by kellnerd** [jesus2099/konami-command#555]
[This release](https://beta.musicbrainz.org/release/6159046a-cb09-42b2-b0d5-3434601e288a) has the same ISRC for each track (which is correct as the whole CD is a single recording) and displays only the ISRC for the first track before it fails with the following error:
```
Uncaught ReferenceError: hasDupeISRCs is not defined
    <anonymous> 6159046a-cb09-42b2-b0d5-3434601e288a line 1 > injectedScript line 398 > eval:1
    createStuffFragment mb. INLINE STUFF.user.js:398
    isrcFish mb. INLINE STUFF.user.js:329
    ue instrument.js:223
    r helpers.js:71
```
This used to work the last time I remember opening such a release.

**Comment by jesus2099** [comment]
Yes, it used to work with all ISRC make as duplicates.
Thanks for your report.

**Comment by jesus2099** [comment]
Oh yes I know why!
I saw this problem already but forgot to fix it!
It will be quick fix, next time I go to my computer.
 🖥️🖱️

**Comment by jesus2099** [comment]
It's fixed, @kellnerd, thanks. :)
BTW: Please uninstall INLINE-TRACK-ARTIST if you have it.
It has been merged into INLINE-STUFF.
