### ISSUE TITLE
FUNKEY does not like pending artist credit edits for RGs

### ISSUE THREAD

**Issue by kellnerd** [jesus2099/konami-command#559]
Hovering over a big cover of a release group whose artist has a pending artist credit edit shows a tooltip that contains JSON-Code after the artist name, e.g. for both covers on [this artist page](https://beta.musicbrainz.org/artist/1fa8c58d-5f2c-4b6a-a3f0-7446104327ec):
![screenshot](https://user-images.githubusercontent.com/52860029/107798991-2aa87000-6d5d-11eb-858a-9c825fc94365.png)

**Comment by jesus2099** [comment]
Since React is used in MBS, more and more JavaScript funny stuff is happening. ;)
Thank you.
