### ISSUE TITLE
Preferred MBS interaction with other script causing error

### ISSUE THREAD

**Issue by psychoadept** [jesus2099/konami-command#562]
FYI, Preferred MBS is having a weird interaction with the CAA Dimensions script. Original discussion is here: https://github.com/ROpdebee/mb-userscripts/issues/8

**Comment by jesus2099** [comment]
Oh.
So the problem is when both scripts are active and you have configured `https://beta.musicbrainz.org` as preferred MB?
Then you go to an open edit list and try to submit votes?

**Comment by psychoadept** [comment]
I think it was the opposite, actually. I was in beta and and MBS was still pointing to the regular site.

**Comment by jesus2099** [comment]
Then it's strange that it says `null` but it's quite normal that MBS warns you when you come from another server (beta).
It's an MBS new security feature.

**Comment by psychoadept** [comment]
The thing is, it only happens in combination with the other script. Otherwise it's not a problem.

**Comment by jesus2099** [comment]
Hmmm.
I am not sure I understand completely.
English is not my natural language.

If there is still a problem, please tell me the precise situation of when the big occurs when preferred MBS and CAA dimensions are active at the same time :

- your `preferredMBS` setting
- the address of the page you are at
- the action(s) you do

And it does not happen if CAA dimensions is turned off or preferred MBS is turned off?
