### ISSUE TITLE
Issue with highlighting different track artist on recording pages

### ISSUE THREAD

**Issue by culinko** [jesus2099/konami-command#573]
Hi, I am creating the issue for highlighting the different artist AC as requested in [MBS-10355](https://tickets.metabrainz.org/browse/MBS-10355). These are my settings:

Chrome: Version 89.0.4389.90 (Official Build) (64-bit)
Script engine: Tampermonkey 4.11
Script version: mb. INLINE STUFF 2021.2.11.1823
Stylus version 1.5.17 with the stylesheet code that you provided in [MBS-10355](https://tickets.metabrainz.org/browse/MBS-10355)

I have reproduced the issue without any other Chrome extensions and without any other Tampermonkey userscripts enabled on the following mb recording: https://musicbrainz.org/recording/064893f0-760f-4ab0-b612-f4ae737d1644. Adding the picture for reference here as well:

![image](https://i.imgur.com/tK4dyQo.png)

What is interesting, is that I can see the highlight correctly on recording https://musicbrainz.org/recording/6018760e-e8e5-4041-8ab7-22b17b8e90b0:

![image](https://user-images.githubusercontent.com/11700272/111907450-9d3ff600-8a55-11eb-8397-353f4b910d94.png)

I can also see the highlight properly on the recording you linked in [MBS-10355](https://tickets.metabrainz.org/browse/MBS-10355), so perhaps this means that if individual AC is the same, but the join phrase is different, the script assumes that it's the same AC? So do you think you could add the join phrase to the AC check as well?

On a related note, ACs will have their mbids with the upcoming schema change on May 17 (ticket for this is in [MBS-11456](https://tickets.metabrainz.org/browse/MBS-11456)), so maybe afterwards the track AC mbid could just be compared with the recording AC mbid?

Thanks for taking a look into this, greatly appreciated :)

**Comment by jesus2099** [comment]
Jojo (second example) is highlighted because MBS indicates it as a name variation.
My script does nothing for it, only the user style makes it visible.

JoJo Ft. Bow Wow (first example) is not marked as name variation by MBS because each artist is in its main form.
So my script could detect artist credit. It does not do it ~~yet~~ any more.

**Comment by jesus2099** [comment]
https://tickets.metabrainz.org/browse/MBS-10355 added a new `.artist-credit-variation` class on JoJo Ft. Bow Wow and track AC that are different from recording AC.

If you use SUPER TURBO's SPOT_AC, it will now be highlighted.
If you don't, you can add a user style on .artist-credit-variation that Réo added with this ticket.
