### ISSUE TITLE
Add option for disabling recording(/track) comments

### ISSUE THREAD

**Issue by Freso** [jesus2099/konami-command#583]
mb_INLINE-STUFF and [Musicbrainz UI enhancements](https://github.com/murdos/musicbrainz-userscripts/blob/master/mb_ui_enhancements.user.js) both append Recording disambiguations to Release track lists. Your script already has a number of configuration toggles in it, so it might make more sense to include an option for this in yours rather than the murdos repo one.
![Screenshot of part of the track list for “Somebody Done Hoodooed the Hoodoo Man” illustrating the problem](https://user-images.githubusercontent.com/177659/115145808-014cde80-a043-11eb-9f83-22067946eb29.png)

**Comment by jesus2099** [comment]
I must check that userscript I didn't know yet.
If it does what INLINE STUFF does (and more?) I will drop my script. :)

**Comment by jesus2099** [comment]
I have added your option, @Freso! :)
The setup box is becoming quite big.
I wonder if anyone is using the other options.
