### ISSUE TITLE
External link query selectors aren’t escaped properly

### ISSUE THREAD

**Issue by mwiencek** [jesus2099/konami-command#599]
We're seeing a lot of errors reported to Sentry that look like this:

```JS
SyntaxError: Failed to execute 'querySelector' on 'Element': 'ul.external_links > li a[href$='//duckduckgo.com/?q=Doin'%20My%20Time']' is not a valid selector.
```

which I believe are coming from mb_ALL-LINKS.user.js.  I guess just the `'` need escaping, not sure about anything else.  (Ideally we'd ignore these errors, but we're already setting the `whitelistUrls` option on our Sentry client, so I'm not sure why these errors are still being sent...)

**Comment by jesus2099** [comment]
Hi Bitmap,
On what page do you have this error?
On https://musicbrainz.org/release-group/fc2be075-281a-4ade-8ca0-eb49669ec381 for example?
I am using the [beta version of mb. ALL LINKS](https://github.com/jesus2099/konami-command/issues/488) and it does not show this error, although it is using apparently the same bad code as [master version](https://github.com/jesus2099/konami-command/blob/2f80c734677dad289a0a88f892991152137c42aa/mb_ALL-LINKS.user.js#L484-L495).

**Comment by mwiencek** [comment]
Yea, I have the master version installed with greasemonkey in Firefox and get an error in the console with that link:

```
Script error in [Greasemonkey script https://github.com/jesus2099/konami-command/mb. ALL LINKS; version 2021.6.6]:
SyntaxError: Element.querySelector: 'ul.external_links > li a[href$='//duckduckgo.com/?q=Doin'%20Time%20With']' is not a valid selector
```

Here's another example: https://musicbrainz.org/recording/50117c0b-d9cf-461b-b227-f680c18087e8

**Comment by mwiencek** [comment]
But FWIW all the errors I looked at are from people using Chrome, so not specific to Firefox.

**Comment by jesus2099** [comment]
You see the errors of other users?

**Comment by jesus2099** [comment]
Yes, wow! :open_mouth: 

> https://chatlogs.metabrainz.org/libera/musicbrainz/msg/4828630/
> _Sentry is something to see what JavaScript errors all MB users have_
> _right, any unhandled exceptions are sent there_
> _Normally, I would not update master version of mb. ALL LINKS because there is this beta version that will soon replace it._
> _But [as] it hinders your logs, I will try to fix this._

**Comment by jesus2099** [comment]
Thanks @mwiencek, it is now fixed both on master and on _All Shook Up Links_ (beta) branches.
Is this _Sentry_ thing visible somewhere?

**Comment by mwiencek** [comment]
Thank you!  The Sentry instance is private but I can let you know if the issue persists.
