### ISSUE TITLE
Save customised links to local storage

### ISSUE THREAD

**Issue by Lotheric** [jesus2099/konami-command#61]
Hi,

I think it would be nice to save user-prefered links to local storage so it won't be overwritten by a script auto-update.

**Comment by jesus2099** [comment]
Oh yes : **Especially with auto‐updates, indeed !**
When I wrote those hard coded settings I didn’t even know auto‐updates (opera’s plain userjs engine doesn’t have that).

**Comment by pankkake** [comment]
It's the reason I'm using an old version (just installed it again and I can see it changed a lot!) - I have added and removed a lot of things.

Though, I guess I could fork publicly, and rebase regularly my version and thus benefit from easy updates on all my browsers…

**Comment by jesus2099** [comment]
@pankkake, you can also install the latest version, then setting the version number to `2099.6.6.6` (or anything in the distant future) should prevent any automatic updates. :stuck_out_tongue_winking_eye:
But yes, without this live **user settings** feature, it’s terrible, I agree… :disappointed:

**Comment by jesus2099** [comment]
All changes to ALL LINKS should be done in `#61-protect-user-customised-ALL-LINKS` branch until #61 is OK.

**Comment by jesus2099** [comment]
@Lotheric @pankkake could you save your settings to a text file? For the last time.
I hope soon enough I will fix this ticket. When it is fixed, it will overwrite your settings but only this last time.

**Comment by Lotheric** [comment]
I'm ready, go ahead with any chnages you planned :)

**Comment by jesus2099** [comment]
If you want to test this in beta phase, there is no GUI to edit settings yet.
You can use **mb_LOCAL-STORAGE-MANAGER** to manually set some settings ; examples : 

local storage key | description | example value
----------------------|----------------|-------------------
jesus2099_all-links_enabled-default-autolinks | show/hide default autolinks | `{"Web pages": true, "Web pages (strict)": false, "Images": true, "Videos": true, "Credits": true, "SACEM (Interprète)": true, "SACEM (Auteur‐Compositeur‐Éditeur)": true, "JASRAC（アーティスト）": true, "JASRAC（著作者）": true, "音楽の森（アーティスト）": true, "音楽の森（著作者）": true, "Lyrics": true, "decoda": true, "LyricWiki": true, "うたまっぷ（アーティスト）": true, "うたまっぷ（作詞者）": true, "うたまっぷ（作曲者）": true, "J-Lyric（歌手）": true, "歌詞タイム": true, "Japanese stuff": true, "VGMdb": true, "ja.Wikipedia": true, "CDJournal search": true, "Joshinweb search": true, "Yunisan": true, "VKDB": true, "Vietnamese stuff": true, "vi.Wikipedia": true, "nhạc số": true, "Korean stuff": true, "maniadb": true, "Other databases": true, "AllMusic": true, "Discogs": true, "ISNI": true, "Rate Your Music": true, "Second hand songs": true, "WhoSampled": true, "Other stuff": true, "en.Wikipedia": true, "*.Wikipedia": true, "Lastfm (mbid)": true, "Lastfm (name)": true, "BBC Music": true}`
jesus2099_all-links_languages | displayed languages for wikidata to wikipedia page feature | `["fr", "en", "vi", "ja"]`
jesus2099_all-links_user-autolinks | your own autolinks (you can use `%artist-id%` (MBID), `%arist-name%`, `%artist-sort-name%` and `%artist-family-name-first%` only at the moment, no other entities yet) | `{"xyz": "//duckduckgo.com/?q=%artist-name%+xyz", "XYZ": "//duckduckgo.com/?q=%artist-name%+XYZ", "abc": "//duckduckgo.com/?q=%artist-name%+abc"}`

In this example, the only disabled default autolink is **web search (strict)**.

All keys (search link text) must be **unique** in user autolinks (and `xyz` **is** different from `XYZ`, so they are unique too in this example).

It is not guaranteed it will remain exactly the same so maybe you will have to do stuff when it updates again but probably not.

User autolinks will be alphabetically sorted.

**Comment by jesus2099** [comment]
* [x] Make the user settings work
* [ ] Add a GUI to manage the user settings

**Comment by jesus2099** [comment]
I have done it at last. It seems I am too late for @pankkake, whom I don't see editing MB any more... :/

- The default autolinks enabler/disabled is quite decent but category headers will be displayed even when empty.
- The user autolinks editor is a monstrously raw prompt.
- The wikidata to Wikipedia expander (#148) language preference is also an ugly prompt. But it may be more acceptable s its content is small.

At least, it is better than nothing, until it gets better.
And it is unlocking quite some other tickets that were blocked by this one.
