### ISSUE TITLE
Highlighting of indirectly related works

### ISSUE THREAD

**Issue by kellnerd** [jesus2099/konami-command#612]
I just realized that the collection highlighter (with highlighting of recordings and works enabled) does not only highlight works with a **recording-work** relationship ("recording of") but also works with **work-work** relationships (e.g. "is based on") which are also shown on release pages.
This surprised me, since I would not consider these works as "owned" if I do not have a "direct" recording of these. Is this intended behaviour or just a side-effect?

https://github.com/jesus2099/konami-command/blob/5f985f89b2a804a55efd7e272dcd5a38b732d77b/mb_COLLECTION-HIGHLIGHTER.user.js#L223-L241

I can't really tell from the code since I never used XPath but I guess this is the place that matches all entity links and I found nothing that would filter (works) based on relationship types.

**Comment by jesus2099** [comment]
Thanks @kellnerd.
It used to not embark the base or derivate works.
So a recent (?) change must have broken this.

**Comment by jesus2099** [comment]
Do you remember the release where you had the issue?
Was it with initial loading (**My Collections** page) or with dynamic loading (**release** page).

**Comment by kellnerd** [comment]
I was adding [The Many Faces of Pink Floyd](https://musicbrainz.org/release/9d2340af-5194-40a0-b099-944fb2d3a5ef) to one of my highlighted collections (dynamic loading) which has lots of these work-work-relationships, otherwise I might not have noticed it.

**Comment by jesus2099** [comment]
https://tickets.metabrainz.org/browse/MBS-11871

**Comment by jesus2099** [comment]
I reproduced the bug:

- Collections page, Append/Reload/Load: :o: OK
- Release page, Credits at bottom: :x: NG
- Release page, Inline credits: :o: OK

**Comment by jesus2099** [comment]
A possible work around
--------------------------

Replace:

```js
var checks = getStuffs();
```

With:

```js
var backToBottom = false;
if (button#toggle-credits is inline) {
	backToBottom = true;
	click button#toggle-credits;
}
var checks = getStuffs();
if (backToBottom) {
	click button#toggle-credits;
}
```

**Comment by jesus2099** [comment]
Another possible work-around
----------------------------------

If bottom credits, loop through matched works and check if their td previous sibling is th containing _recording of:_ (or equivalent).

**Comment by jesus2099** [comment]
Another possible work-around
----------------------------------

**Migrate dynamic collection updater to Web Service mode** #64

**Comment by jesus2099** [comment]
Blocked by #64.

**Comment by jesus2099** [comment]
This is no longer blocked if I make #64.

**Comment by jesus2099** [comment]
It should be fixed!

**Comment by jesus2099** [comment]
Yes it works! it does no longer highlight _is based on_ and _revision of_ with the example release!

https://musicbrainz.org/release/9d2340af-5194-40a0-b099-944fb2d3a5ef
