### ISSUE TITLE
"My edit notes on my edits" probably is not that cool

### ISSUE THREAD

**Issue by kellnerd** [jesus2099/konami-command#613]
While I like the idea to show these cool links (and already used these searches in the past to recall whether I had already interacted with an editor before), it makes no sense to have them on your own profile:

![image](https://user-images.githubusercontent.com/52860029/129404088-eccb64a9-4183-460d-b1b8-cc9a66981ef5.png)

**Comment by jesus2099** [comment]
Ha ha! Sure! 🤭

**Comment by jesus2099** [comment]
Now it won't appear if you are not logged in or if you are on your own profile page.
