### ISSUE TITLE
USER_STATS: MBS now shows total

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#648]
## Without script

![before](https://user-images.githubusercontent.com/1401086/145697869-42fdcfb0-c2cc-4479-a935-3768b35f3685.png)

## Beta change 

Show total edit count on user pages
https://tickets.metabrainz.org/browse/MBS-12097
https://github.com/metabrainz/musicbrainz-server/pull/2342/files

![after](https://user-images.githubusercontent.com/1401086/145697895-be95c7b7-8883-4b6e-b90d-dd0e9e5b91ed.png)

## With script before change

![script](https://user-images.githubusercontent.com/1401086/145697862-fc0ecd37-f924-493d-b83e-3d91268cfeb6.png)

Script broken in beta.

**Comment by jesus2099** [comment]
Now beta has been deployed to main MBS.
I fixed my code to more sustainable code, based on URL rather than on link positions in the table:

![new](https://user-images.githubusercontent.com/1401086/145828862-d87e94e7-73d3-49f6-bd7a-c8039907b7ce.png)

**Comment by kellnerd** [comment]
Did you perhaps forget to publish the commit with the fix? I was expectantly pressing the update button but there was no update.

**Comment by jesus2099** [comment]
Yes, I didn't push it yet as I wanted to fix some other things in same script, but eventually there are no small bugs to fix any more in it. :)
