### ISSUE TITLE
ROW_HIGHLIGHTER: support RGBA value?

### ISSUE THREAD

**Issue by redactedscribe** [jesus2099/konami-command#660]
Pretty simple, would it be possible for ROW_HIGHLIGHTER in the TURBO userscript to support alpha for the chosen colour?

In certain circumstances, a bit of transparency could help by showing a bit of the original background/cell colours, e.g. the green of an Artist cell in the Tracklist tab when editing a release. Same for the Length cell when its grey due to a discid set for the release medium.

Thanks!

**Comment by jesus2099** [comment]
Well, the row highlighter is a very basic thing, it is not an overlay on the top of existing background, it replaces the original background, completely.
If we would set opacity on it, it would not let the original colour appear.

**Comment by redactedscribe** [comment]
I was thinking that may be the case. Since the "feature" tag has been added to the issue, I assume alpha values may by supported one day. Thanks for considering the idea.

**Comment by jesus2099** [comment]
Next time I have time for this, I will see if it would be simple or just too much work.

**Comment by jesus2099** [comment]
Hello @redactedscribe, I have allowed the use of `rgba(…)` in the ROW_HIGHLIGHTER settings.
But, as I said, this is not a colour over the existing colour.
The new colour replaces the initial colour.
If it is semi-transparent, the background colour that is behind and to which it will blend is the page background, which is white. :)

But maybe ROW_HIGHLIGHTER will be integrated in MBS itself! See #705.
