### ISSUE TITLE
Dynamic loader fails when optional entities are not checked

### ISSUE THREAD

**Issue by ToadKing** [jesus2099/konami-command#665]
# COLLECTION HIGHLIGHTER: Exception when trying to add a release #

Trying to add [this release](https://musicbrainz.org/release/53c7f78e-dbc8-4dc6-85c2-cb8ffcf31237) logs this error in my console:

```
Uncaught TypeError: can't access property "indexOf", stuff[type].rawids is undefined
    addRemoveEntities mb. COLLECTION HIGHLIGHTER.user.js:628
    browseReleases mb. COLLECTION HIGHLIGHTER.user.js:535
    loadReleases mb. COLLECTION HIGHLIGHTER.user.js:479
    r helpers.js:71
    _wrapEventTarget trycatch.js:74
    ce instrument.js:328
    loadReleases mb. COLLECTION HIGHLIGHTER.user.js:473
    collectionUpdater mb. COLLECTION HIGHLIGHTER.user.js:725
    r helpers.js:71
    _wrapEventTarget trycatch.js:74
    ce instrument.js:328
    collectionUpdater mb. COLLECTION HIGHLIGHTER.user.js:712
    VMin028ifn5j1 mb. COLLECTION HIGHLIGHTER.user.js:220
    VMin028ifn5j1 mb. COLLECTION HIGHLIGHTER.user.js:1145
    VMin028ifn5j1 mb. COLLECTION HIGHLIGHTER.user.js:1145
    a injected-web.js:1
    v injected-web.js:1
    set injected-web.js:1
    <anonymous> mb. COLLECTION HIGHLIGHTER.user.js:1
    c injected-web.js:1
    ScriptData injected-web.js:1
    onHandle injected-web.js:1
    c injected-web.js:1
```

(Due to how Violentmonkey works, subtract 138 from the script line numbers to get the actual number)

Script version: 2022.1.23
Userscript manager: Violentmonkey
Browser: Firefox Nightly 98.0a1 (2022-01-26) (64-bit)

**Comment by jesus2099** [comment]
Linux Debian 10
Firefox 91.5.0esr (64 bits)
Violentmonkey 2.12.10
mb. COLLECTION HIGHLIGHTER version 2022.1.23

I tried _ON_ and _OFF_ links, OK.
Then I tried _Add to collection_ then _Remove from collection_, they worked too, with no errors.

**Comment by ToadKing** [comment]
It looks like it might be something with my collection stuff that's corrupted. `stuff.label` is this for me:

```
{ rawids: undefined, loaded: true, ids: null }
```

Let me try refreshing my collection and trying again.

**Comment by jesus2099** [comment]
On your collections page, near the (Re)Load link, did you check to load labels or not?
If you open the script code with Violentmonkey, there is a _Values_ tab, between _Configuration_ and _Require_. Does the content of labels, releases, etc. look correct, in there?

**Comment by ToadKing** [comment]
That might be it. I have the "Labels" option unchecked and there's no labels field in the values tab.

![image](https://user-images.githubusercontent.com/1023440/151265067-34440860-2768-41a4-a32b-af3d01dc31b6.png)

**Comment by jesus2099** [comment]
Windows 10
Vivaldi 5.0.2497.48 (Stable channel) (64 bits)
Violentmonkey 2.13.0
mb. COLLECTION HIGHLIGHTER 2022.1.23

I tried _ON_ and _OFF_ links, OK.
Then I tried _Add to collection_ then _Remove from collection_, they worked too, with no errors.

**Comment by jesus2099** [comment]
Actually, I usually don't highlight labels either.
But for this new version, I thought I should turn them ON to check if it works.
I didn't try the script again when turning them back OFF, apparently!
Thanks very much for the report, @ToadKing! 😃👍

**Comment by ToadKing** [comment]
Not sure if this warrants another bug being opened, but the fix seems to have broken something else and I can't seem to add any releases to the highlighter now. I uninstalled/reinstalled the script and tried to reload my collection but nothing loaded. The values tab in Violentmonkey only has the collections values and the "cfg" values

**Comment by jesus2099** [comment]
Thank you, I will test.

**Comment by jesus2099** [comment]
Add a work around, please check all entity types in the settings.

**Comment by ToadKing** [comment]
I tried that and it still doesn't seem to work.

Values looks like this:

![image](https://user-images.githubusercontent.com/1023440/151641683-535285dc-9ed9-4731-a941-efeb4a47d124.png)

**Comment by jesus2099** [comment]
@ToadKing, I have forced all entity highlights and it works now, as a temporary work-around.
When I said it works with all entities checked, it's because I already had that modified version locally, I forgot I did not push it to public.

I keep this ticket open.
I will first reorganise my `loadReleases` code to make it external and used by MASS MERGE as well.
Then I will re-enable the settings.

**Comment by jesus2099** [comment]
Hi @ToadKing, I think this time, I fixed this bug, for real.
Please tell me again. 😅

**Comment by ToadKing** [comment]
@jesus2099 Did a reload with the new version and it seems to work with the "Labels" box unchecked. Thanks!
