### ISSUE TITLE
Feature: INLINE STUFF: toggle ISRCs and AcoustIDs from showing

### ISSUE THREAD

**Issue by redactedscribe** [jesus2099/konami-command#685]
As far as I know, there isn't a way to toggle the ISRCs or AcoutIDs from showing next to each recording on a release. A toggle could be added to the same position as the "Display Credits Inline" button above a release (the first link is by another script):

![11111](https://user-images.githubusercontent.com/25013746/171922231-dc24e3e5-a822-4b89-84ac-e8848c87143e.jpg)

With a toggle, now all inline information could be hidden leaving only the tracks/recordings on display.

Thanks.

**Comment by jesus2099** [comment]
Hello @redactedscribe,
There is already a rifle for each, look at the sidebar, where, inside a light gray dashed box, you should see:

> ISRCs: x (hide)
> AcoustIDs: x (show)

Just click **show** or **hide**. 😁

**Comment by jesus2099** [comment]
But maybe I should leave them **always showing** when we click _display credits in line_ and **always hidden** when clicking _show credits at bottom_?

Maybe that was your suggestion?

**Comment by jesus2099** [comment]
You can make a ticket for the highlight other same AcoustID/ISRC.
It would work only if they are in the visible window, though.

BTW here is a tip maybe you don't know: Even if AcoustID are shown in a compact way, they are only visibly trimmed.
If you go to [a release](https://musicbrainz.org/release/5969be5e-c541-3c2b-b1e1-1fc58ff9817d), show AcoustID and they Search in page a full AcoustID that you have copied from somewhere, like `9b4ec895-1d2a-4f6f-b01d-0e5af6b19121` you will find it!

Also there are two shortcuts to link (+) or unlink (×) AcoustID.
