### ISSUE TITLE
Mass collapsed edits can't be expanded one by one

### ISSUE THREAD

**Issue by kellnerd** [jesus2099/konami-command#693]
After having collapsed all edits of the same type/editor (CTRL/ALT click), I can no longer expand them one by one with a simple click. Only the arrow icon changes, but the clicked edit is not expanded anymore:

![image](https://user-images.githubusercontent.com/52860029/175828591-da2d5720-b1d6-499b-97df-76f92bcf70f6.png)

I can only expand all these edits at once (CTRL/ALT click again). Probably related to https://github.com/jesus2099/konami-command/commit/312218ccf5f7ad2964b66a04b2bc0cc3e4fd2132?

**Comment by jesus2099** [comment]
Ach, I forgot about my local patched version and lost it long ago.
I will re-fix this when working on this script again, for several tickets.

Sorry.

**Comment by jesus2099** [comment]
It is because of the `ninja` CSS class.
I don't remember the purpose of this, additionally to the `display: none;` inline styles…

**Comment by jesus2099** [comment]
Fixed at last!

**Comment by jesus2099** [comment]
Thanks for the quick report!
What do you prefer, until it is fixed?

**Comment by jesus2099** [comment]
Thanks so much @nimuxoha, it should be fixed now. :)
