### ISSUE TITLE
Acoustid is not shown

### ISSUE THREAD

**Issue by Alfge** [jesus2099/konami-command#707]
Acoustid is not shown when release has many CDs. In this case the acoustid is shown from the first four CDs, but not for all the rest, for which the tracklist must be opened extra.
(This is not the right description. Please take a look yourself on the release https://musicbrainz.org/release/83600067-8db6-4142-b6d3-6047a723f524)

Alfg

**Comment by jesus2099** [comment]
Thanks @Alfge for the report, but this bug is already filed as #38.
