### ISSUE TITLE
Libraries (require) not loaded depending on run-at

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#708]
I had my laptop reset.
And since then I have some problems: #708, #709, #710

---

My userscripts with `// @require` libraries and without exactly `// @run-at document-start` (either none or other value), have the libraries not loaded by Violentmonkey.

```js
// ==UserScript==
// @name         New OK script
// @require      https://github.com/jesus2099/konami-command/raw/de88f870c0e6c633e02f32695e32c4f50329fc3e/lib/SUPER.js?version=2022.3.24.224
// @run-at       document-start
// ==/UserScript==
"use strict";
console.log("NEW OK SCRIPT");
createTag("span", {}, "test");
```

![image](https://user-images.githubusercontent.com/1401086/191765802-6ce8e944-af49-4f17-b5f0-8f372823fbf9.png)

**This works** with `// @run-at       document-start` !?

```js
// ==UserScript==
// @name         New NG script
// @require      https://github.com/jesus2099/konami-command/raw/de88f870c0e6c633e02f32695e32c4f50329fc3e/lib/SUPER.js?version=2022.3.24.224
// ==/UserScript==
"use strict";
console.log("NEW NG SCRIPT");
createTag("span", {}, "test");
```
![image](https://user-images.githubusercontent.com/1401086/191765853-25b1a458-cb0d-4536-bc79-9afb86612d11.png)

**This does not work**, the SUPER.js code is not append.
I also tried `// @run-at       document-ready` and `// @run-at       document-idle` both no good (NG), as well.

Other values than `document-start` are blocking the `@require` loading.
**OK script must be first in the list and NG script must be second in the list, to reproduce the bug.**
So maybe it's not only related to `run-at`.

- https://github.com/violentmonkey/violentmonkey/issues/1581
- https://github.com/violentmonkey/violentmonkey/issues/1580

---

I don't know what has changed except that I had to install programs as non-admin, in `%LocalAppData%\Programs\`

- **Windows** 10 **Vivaldi** 5.4.2753.51 (Stable channel) (64 bits) 
- **Android** 9 **Kiwi Browser** 105.0.5195.33 **Violentmonkey** 2.13.1
- **Windows** 10 **Chrome** 105.0.5195.127 (Build officiel) (64 bits)
- **Violentmonkey** 2.13.1

(I don't remember previous versions)

**Comment by jesus2099** [comment]
Reproduced on Android 9 Kiwi Browser 105.0.5195.33 Violentmonkey 2.13.1

![Screenshot_2022-09-23-17-30-00-655_com kiwibrowser browser](https://user-images.githubusercontent.com/1401086/191998017-504776d2-3bdc-472a-93db-695574a99c8a.jpg)

**Comment by jesus2099** [comment]
Also confirmed in **Chrome** 105.0.5195.127 (Build officiel) (64 bits).

**Comment by tophf** [comment]
I see it now. Evidently I've copypasted the code incorrectly.

**Comment by jesus2099** [comment]
The [bug has been fixed](https://github.com/violentmonkey/violentmonkey/issues/1581#issuecomment-1257017578) by @tophf but we now have to wait for next Violentmonkey release.

**Comment by jesus2099** [comment]
The [bugfix](https://github.com/violentmonkey/violentmonkey/commit/070eca76c6c41cd8b5b97a2b0b9293946bbedc07) has been [deployed](https://github.com/violentmonkey/violentmonkey/issues/1581#issuecomment-1294574032).
