### ISSUE TITLE
Mimic MBS edit note validation and warnings

### ISSUE THREAD

**Issue by thomasboehm** [jesus2099/konami-command#712]
When merging release groups, I get the warning about the destructive edit and after clicking OK it goes back and the edit note field is highlighted in red. What am I doing wrong?

![Selection_077](https://user-images.githubusercontent.com/9038242/195594842-bec8350d-cf24-41c6-b0ff-2530df2dca11.png)

Firefox 105.0.3
Greasemonkey 4.11
Kubuntu 22.04

**Comment by jesus2099** [comment]
It's the same if you don't use the userscript.

![image](https://user-images.githubusercontent.com/1401086/195635575-7e5b07d0-ff72-4368-bcda-ab86f0afae11.png)

Merging entities is a destructive edit.
You must know what you are doing and you must explain it in the edit history, why you are merging, why you think they are the same.

I will change my scripts (MERGE HELPOR 2 and MASS MERGE RECORDINGS) to mimic MBS, using the same error messages and styling.

**Comment by jesus2099** [comment]
Ah sorry, I see that you did write an edit note:

> duplicate release group

My scripts are validating edit notes and they think this one is not enough. 🤣 
I will maybe lower the threshold of validation.

**Comment by jesus2099** [comment]
Notes to myself:

https://github.com/metabrainz/musicbrainz-server/blob/769a6e36d30f7529ed836f83b3ce7e5615700a96/lib/MusicBrainz/Server/Form/Role/EditNote.pm#L19-L29

- You must provide an edit note
- Your edit note seems to have no actual content. Please provide a note that will be helpful to your fellow editors!

https://github.com/metabrainz/musicbrainz-server/blob/769a6e36d30f7529ed836f83b3ce7e5615700a96/lib/MusicBrainz/Server/Validation.pm#L303-L316

https://github.com/metabrainz/musicbrainz-server/blob/769a6e36d30f7529ed836f83b3ce7e5615700a96/root/static/scripts/release-editor/init.js#L285-L291

**Comment by thomasboehm** [comment]
Maybe you could lower the threshold for **release groups** only. Two release groups with the same name are very rarely correct.

In the last few weeks/month I see a lot of new users using some scripts to scan their music collection and adding release groups even if there is already one.

In my example the band 10cc had their last release 27 years ago, yet some newbie thought he should add each album with a new release group.

https://musicbrainz.org/artist/f37c537b-3557-4031-bfd6-ab63ced32854

Maybe Musicbrainz should make it much harder for new users to create release groups.
