### ISSUE TITLE
Update the Apple Music logo used in the sidebar

### ISSUE THREAD

**Issue by Lotheric** [jesus2099/konami-command#733]
The Apple Music logo should be the preferred one from

https://www.apple.com/itunes/marketing-on-music/identity-guidelines.html#apple-music-icon

White notes on red background.

It's apparently cached or changed by the script "mb. ALL LINKS"
see https://tickets.metabrainz.org/browse/MBS-12736

**Comment by Lotheric** [comment]
It seems to be affecting the BnF favicon as well...
see on https://musicbrainz.org/artist/0fb04a47-2c27-4598-9fbc-b90ac573cb97

**Comment by jesus2099** [comment]
I see in their html pages, they point to some other icons:

- https://music.apple.com/assets/favicon/favicon-16.png
- https://catalogue.bnf.fr/images/icones/icone_CG.png

But the script is using whatever icon they have placed in their servers:

- https://music.apple.com/favicon.ico rainbow note (looks nice)
- https://catalogue.bnf.fr/favicon.ico white square (lol)

I will update the hard coded `faviconClasses` list from https://github.com/metabrainz/musicbrainz-server/commit/27cb730d712c5ffad81aa41fbec9ff7ab10b6526

**Comment by jesus2099** [comment]
Done.

**Comment by Lotheric** [comment]
Yay It works! Thanks.
