### ISSUE TITLE
Edit note added in relationship editor is lost upon submission

### ISSUE THREAD

**Issue by nimuxoha** [jesus2099/konami-command#751]
When using ELEPHANT EDITOR to add edit notes in the new relationship editor (still in beta but might soon be released) the note  is suddenly cleared and omitted from submitted edits once "enter edit" is clicked or when <kbd>SHIFT</kbd> Clicking on a stored note.

It can be worked around by manually typing something in the edit note field. So it seems not to detect the note when it's added by the script alone.

**Comment by kellnerd** [comment]
@jesus2099 I had the same problem with my userscripts, edit notes are now React-ified too.
My solution: https://github.com/kellnerd/musicbrainz-scripts/commit/38e700956b652c9efcc13a35297e4da9e744e330 & https://github.com/kellnerd/musicbrainz-scripts/commit/bf7da06d3cb397d2bd12fb230d9c7592b2a17f90

**Comment by jesus2099** [comment]
Thanks for reporting @nimuxoha and thanks for the diagnostic @kellnerd!

I already had to use [this trick](https://community.metabrainz.org/t/musicbrainz-userscripts-tips-and-tricks/554197/2?u=jesus2099) for the same problem #600 too.
Without your comment I would have probably wasted time understanding before finding this cause back.
😁👍

**Comment by jesus2099** [comment]
I should also make a shared function like you, as now, this problem affects 2 scripts, and probably more, in the future.

**Comment by jesus2099** [comment]
It seems OK now.
Please tell if not. :)
