### ISSUE TITLE
Script doing nothing at all besides adding "Force highlight ON / OFF" text at the release level.

### ISSUE THREAD

**Issue by n-99** [jesus2099/konami-command#770]
Sorry for the vague bug report, but I can't see any difference with the script running besides that added text.

I'm running Windows 7 SP1, Firefox Developer 115.0b9 64-bit (the newest), with an updated Tampermonkey (v4.18.1) and the latest script (2023.6.8). I disabled my ad-blocker and my other MusicBrainz scripts. I added both releases and release groups to various groups, and don't see any chance on the artist, release group or search results page. I don't even know how the highlighted release is supposed to look.

**Comment by jesus2099** [comment]
Hello @n-99,
You must first "load" your release collection.
See [support topic](https://community.metabrainz.org/t/highlight-owned-stuff-releases-recordings-with-mb-collection-highlighter/559889?u=jesus2099)'s link to [Very old _HOW TO_ on that obsolete version page](https://web.archive.org/web/20140327054755/userscripts.org/scripts/show/126380) ← **don’t download/install from there!**

Good luck. ;)
