### ISSUE TITLE
mb. INLINE STUFF - proposed UI. refinements

### ISSUE THREAD

**Issue by fmera** [jesus2099/konami-command#784]
hi jesus2099
just began trying out this script. is there any way to adjust the following:
1. remove the drop-shadows in the track and recording titles when they both appear (a bit distracting)
2. remove the highlights & hyphens (or at least hyphens) in the ISRCs, so i can easily copy the ISRCs as text w/o the hyphens

thks!

**Comment by jesus2099** [comment]
Hello fmera,

1. Is here to show when the track titles are different from recording titles. Underline was too much (more) distracting than that. What would you think of, instead?

2. It's one of the purpose of the script
