### ISSUE TITLE
JASRAC/MINC work search

### ISSUE THREAD

**Issue by julian45** [jesus2099/konami-command#797]
It looks like MINC has updated a couple things in a way that [this userscript](https://github.com/jesus2099/konami-command/blob/master/jasrac-mb-minc_WORK-IMPORT-CROSS-LINKING.user.js) might benefit from. I would make a pull request for this myself, but my JavaScript skills are... more than a little rusty, so I figured this would be a better method than trying to submit spaghetti code. Please let me know if there's anything I can clarify, and if I'm overstepping my bounds as a user here, I sincerely apologize.

MINC's website has undergone a substantial interface refresh from what it used to be. Technically, the system called 音楽の森 is now 音楽権利情報ナビ, but that's a mouthful, and 音楽の森 is short and sweet enough that I don't see enough of a reason to suggest replacing the name in the userscript. (Or, 音楽の森 could be renamed to just MINC...?)
This refresh includes a couple of changes to request flow:

1. In searches on MINC, queries that once began with `search.minc.or.jp`, like [this portion of the code](https://github.com/jesus2099/konami-command/blob/22a92a8e54e3bb3c7dfed2c7c9c41a99ad4ae022/jasrac-mb-minc_WORK-IMPORT-CROSS-LINKING.user.js#L1054C67-L1054C67), now start with `www.minc.or.jp`. Right now, there is no need to update this part of the code, as MINC automatically redirects; this redirect works for both title- and JASRAC code-based searches, like [here](https://musicbrainz.org/work/27c0069e-016e-455a-972e-45ce36a23a0b).
2. MINC can now search NexTone work codes with only a slight modification to the search query, and I would greatly appreciate it if MINC search by NexTone work code could be added to the script. On the same line I linked above, if you set the `match` parameter to `2` instead of `1` while querying with a NexTone work code, MINC will search with that code. Thus, for the work above, which has JASRAC 707-0251-9 and NexTone N00050360, both of the following links are valid and will return the same work. I've come across some works that are registered with NexTone but don't show up as such in MINC, but those are so few and far between that I definitely don't see a need to query NexTone directly (and that's already been discussed in #748).

```
https://www.minc.or.jp/music/list/?tr=707-0251-9&type=search-form-sakuhin&match=1
https://www.minc.or.jp/music/list/?tr=N00050360&type=search-form-sakuhin&match=2
```

**Comment by jesus2099** [comment]
>  interface refresh

Yes, I only saw that their log in page was so much better now.
Thanks for noticing the rest.
By the way, I can also update the minc searches I have in #244/#488 branch ALL-LINKS.

**Comment by jesus2099** [comment]
It's even 音楽権利情報検索ナビ but it's very long.

**Comment by jesus2099** [comment]
I think I did all what you told, @julian45, thank you again! :)

**Comment by julian45** [comment]
I just updated and tested, and it works well! Thanks so much!!!
