### ISSUE TITLE
Cancel edit templates

### ISSUE THREAD

**Issue by uniquereplica** [jesus2099/konami-command#8]
Hi,

Another request for your consideration similarly to the last one, regarding trying to make cancelling edits more user-friendly.

I am having to do a cancel many many times, as it is not possible to cancel multiple edits in one go. For example, I have made errors in various performer accreditations on a 60 track album and had to roll many of them back for the same reason, it is very repetitive and interactive, as before causing RSI/CTS.

In lieu of more wholescale improvements to how cancel works I was wondering if it would be possible to configure a template cancel message that can be filled in automatically, eg for when you have to cancel 30+ edits that were all being cancelled because the choir master shouldn't have been attached to non-choir tracks, saving me clicking and pasting that same message all of those times.

I certainly don't think a template is suitable for on edit notes, but on a cancel done what do you think?

Thanks

**Comment by jesus2099** [comment]
Here is the latest version: [fast-cancel-edits.user.js](//bitbucket.org/mwiencek/userscripts/src/master/fast-cancel-edits.user.js) ([install](//bitbucket.org/mwiencek/userscripts/raw/master/fast-cancel-edits.user.js)). :)
