### ISSUE TITLE
Elephant Editor 'previous note' button

### ISSUE THREAD

**Issue by Aerozol** [jesus2099/konami-command#811]
Thanks for the amazing script! As I have been using it more, there is one function that I have started wishing for - a 'previous note' button (if possible!)

Because sometimes I do a string of edits that could use the same note, but I want to keep my 'always used' edit notes in the shortcut bar (so I don't want to press 'remember' and shuffle out those ones).

Mockup:
![image](https://github.com/jesus2099/konami-command/assets/26584/917666e3-9d0e-4cb3-9fb7-bd7b9aef262c)

**Comment by jesus2099** [comment]
Great idea!
I called it _permanent memories_ in [my old TO DO list](https://web.archive.org/web/20131103163403/userscripts.org/scripts/show/94629#footer).

The best name could be _favourite notes_?

I guess it could be 3 specific edit note buttons, maybe, but it requires a text area popping up that allows creating/editing them...

**Comment by Aerozol** [comment]
Haha, we use Elephant Editor completely differently! I don't edit with 'remember' ticked... so the 10 existing buttons _are_ my 'favourite notes' :P

For me I would love a single 'previous note' button, but I can see why you don't need it.

**Comment by jesus2099** [comment]
I understand.
In the meantime, I have added a delete feature when you Ctrl+click one of your memories.
It could be little but easier for you when you need to redefine one of your memories.
I must think a way of having _lots_ of templates like you while still saving a few recent notes, and without having to check a save option or anything...

**Comment by Aerozol** [comment]
That is perfect!! That actually solves my use case, if you would like to close this ticket :)

**Comment by jesus2099** [comment]
Then I'm lucky. 😉
