### ISSUE TITLE
Discogs Script Issues

### ISSUE THREAD

**Issue by phoxwater2024** [jesus2099/konami-command#820]
Hi, in the last few days, the Discogs script has started causing a slowdown when viewing discographies pages.  At the same time as the slowdown began, the icons used within the Albums, Singles & Compilation fields increased in size (Screenshot included).  

I'm using Violentmonkey on Brave Browser, Please let me know if you need any more Information from me?
![Screenshot-07-05-2024-19:18:14](https://github.com/jesus2099/konami-command/assets/169191558/43d299fc-47c4-4737-b44e-0d0f009e9c34)

**Comment by jesus2099** [comment]
Hi @phoxwater2024,
This script is not mine, it's Discogs importer, by @murdos.

I didn't see problem with Android 9 Kiwi Violentmonkey, but you can submit your issue again, but over there, at https://github.com/murdos/musicbrainz-userscripts/issues?q=is%3Aissue+is%3Aopen+discogs+importer
