### ISSUE TITLE
Can’t add/remove the same release to/from two highlighted collections

### ISSUE THREAD

**Issue by DoktorSultan** [jesus2099/konami-command#822]
I have a few different collections, but as some overlap, I sometimes add the same release to two different collections.

This is not possible while the collection highlighter script is running.
Currently I need to do a workaround: disable the userscript before adding it to a second collection, then enabling the userscript again.

The workaround works fine and causes no issues, but at first I didn't realise it didn't add the release to the second collection until I was missing a release I was sure I added.

**Comment by jesus2099** [comment]
Can you explain step by step how to reproduce this bug?

I tried this and had no problems, please help:

1. Add to (highlighted) release collection
2. Add to another (not highlighted) release collection

It's added to both.
Is the problem when adding to 2 highlighted collections?

**Comment by jesus2099** [comment]
If I add support for _Add to test collection 2_ (which I should do),

Then we have a problem when it's in _test collection 1_ and _test collection 2_, and I click on _Remove from test collection 1_: 

It will remove release from userscript, although it is still in _test collection 2_.

**Comment by jesus2099** [comment]
Now it works to dynamic update (add and to remove) same release with several highlighted collections!
Thanks again for the bug report, @DoktorSultan.
