### ISSUE TITLE
Acoust ID not shown in MusicBrainz

### ISSUE THREAD

**Issue by Alfge** [jesus2099/konami-command#828]
Hi,
Example: https://musicbrainz.org/release/dd65cf48-cda0-4137-9905-76dd7a9f7bb3

Due to the userscript inline-stuff the acoustid for a release sequence e.g. CD1, CD2, CD3, CD4, CD5 is only displayed for the first three CDs in Musicbrainz. This means that although the tracks for CD 4 and CD5 also have acoustids they are not displayed in the release overview-page. 
This may be due to the fact that you have to explicitly open the track list from the 4th CD of a CD series in MusicBrainz.

best regards
and happy programming
Alfg

**Comment by jesus2099** [comment]
Thanks @Alfge for the report, but this bug is already filed as #38.
