### ISSUE TITLE
Mutation events are deprecated and will be removed from Chrome 

### ISSUE THREAD

**Issue by nimuxoha** [jesus2099/konami-command#835]
Mutation events will very soon be removed from Chrome and it [seems there are still 4 scripts](https://github.com/search?q=repo%3Ajesus2099%2Fkonami-command+%28DOMNodeInserted+OR+DOMNodeRemoved+OR+DOMSubtreeModified+OR+DOMSubtreeModified+OR+DOMCharacterDataModified+OR+DOMNodeInsertedIntoDocument+OR+DOMNodeRemovedFromDocument+OR+DOMAttrModified+OR+DOMAttributeNameChanged+OR+DOMElementNameChanged%29&type=code) of yours that use these

https://chromestatus.com/feature/5083947249172480
https://developer.chrome.com/blog/mutation-events-deprecation

---

- [x] kasi_PLAIN-TEXT-LYRICS f71f86ced7b1128042d71c37065804f70cb3592a
- [x] mb_COLLECTION-HIGHLIGHTER 408d96cadc60c0c96d225949fef023f697269eba
- [x] mb_PREFERRED-MBS 18625930edc12a49df7a22d425e6a80cbd154fc1
- [x] mb_SUPER-MIND-CONTROL-II-X-TURBO 023f8be6d7ab76ed7c7a1e3b84ff06c9328b5104 caf99b7b9caecd62429cda872c3e97108028eb8b 09a6436433a6292a9d3c26bdf110c7fa8641e303

**Comment by jesus2099** [comment]
Thank you @nimuxoha, your kind are very useful!

**Comment by jesus2099** [comment]
Apparently I have already used that `MutationObserver` thing, [three times](https://github.com/search?q=repo%3Ajesus2099%2Fkonami-command+MutationObserver&type=code).

**Comment by jesus2099** [comment]
Thanks again @nimuxoha, I have no more DOM event listeners around.

**Comment by jesus2099** [comment]
@kellnerd spotted a bug in TAG_TOOLS.
I understand the cause. 
I have to fix but am on holidays with no PC. 

I will try on smartphone.
The Violentmonkey editor world on smartphone, but not sure with the GitHub editor, we'll see...

**Comment by jesus2099** [comment]
@kellnerd it should be ok with version 2024.7.10.1738 but I hope I did not break some other use cases, like on different pages...

**Comment by kellnerd** [comment]
Yes, I can use the tag input again without fear.
Thank you for fixing that so fast, but now enjoy your holidays please 🌴

**Comment by jesus2099** [comment]
Thank you! 😁❤️
