### ISSUE TITLE
USER_STATS: Percentage calculation fails when cell is empty

### ISSUE THREAD

**Issue by nimuxoha** [jesus2099/konami-command#836]
It seems when one of the cells under "added entities" is empty the whole calculation fails and shows `NaN` everywhere instead:

![beta musicbrainz org](https://github.com/jesus2099/konami-command/assets/29738614/d5464b7f-d745-4119-a066-1c8282c5e21f)

This is currently in beta ([MBS-13647](https://tickets.metabrainz.org/browse/MBS-13647))
https://github.com/metabrainz/musicbrainz-server/pull/3301

**Comment by jesus2099** [comment]
It's an MBS bug, kind of. 
Usually when it's 0 added entities, the whole row does not appear.

**Comment by jesus2099** [comment]
So apparently it's just a [temporary glitch...](https://github.com/metabrainz/musicbrainz-server/pull/3301#issuecomment-2197394031)

**Comment by jesus2099** [comment]
Thank you for reporting, @nimuxoha, I have decided to fix it, even if it is rare and temporary. :)
