### ISSUE TITLE
No longer working on Beta

### ISSUE THREAD

**Issue by Aerozol** [jesus2099/konami-command#840]
OS: Windows 10 Pro
Browser: Chrome Version 127.0.6533.100 (Official Build) (64-bit)

Elephant editor no longer loads for me, on any edit pages, when in beta. It is still showing as 'active' when loading beta edit pages.
Tested with all other scripts turned off, console throws no errors.

**Comment by jesus2099** [comment]
Thank you very much for retiring this, @Aerozol.
It was because of a recent change of mine!

It is fixed, now.

**Comment by Aerozol** [comment]
Woohoo, thank you for the quick fix! I didn't realise that I can't live without this userscript until it went away 😅
