### ISSUE TITLE
Drop release editor UP/DOWN feature

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#842]
See if MBS-13724 is good enough to drop my feature. 

> [MBS-13724](https://tickets.metabrainz.org/browse/MBS-13724): [Make up/down keys move between tracklist inputs](https://github.com/metabrainz/musicbrainz-server/pull/3355)

**Comment by jesus2099** [comment]
I made a recent regression with track number field, or maybe it's because of MBS new UP/DOWN feature. 

It no longer selects whole field value. 

https://github.com/jesus2099/konami-command/commit/67422bbe9c913b7086aba60fd6ee74e7b9d8fe0c
https://github.com/jesus2099/konami-command/commit/492ce2fe2be392df6c6d1c5e94a8fed3e2a13704
https://github.com/jesus2099/konami-command/commit/625ba7b5fab669ed8917b3dbd8d67b297fc87a5b

**Comment by jesus2099** [comment]
It seems to be because of MBS new UP/DOWN feature...

**Comment by derat** [comment]
IIRC the MBS code sets the selection after focusing the input to position the caret at the beginning or end of the input. If that event listener is running after your userscript's event listener, maybe it's clearing the selection. Calling [stopImmediatePropagation](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopImmediatePropagation) in your listener might prevent the server's listener from running.

**Comment by jesus2099** [comment]
Wow MAGIC!!
It works!!
Thank you, @derat!

**Comment by jesus2099** [comment]
Actually, `stopPropagation` is even enough.
I was only using `preventDefault`, also needed, but not enough.

Should I use `preventDefault` and `stopPropagation`, which are already enough?
Or should I go YOLO `preventDefault` and `stopImmediatePropagation`, to be more drastic for future proof...? :)

**Comment by jesus2099** [comment]
I think I keep my own UP/DOWN release tracklist edit feature because, although MBS-13724 is really good, I miss those additional features: 

- Jump between tracks, even if the caret is not at the start of end of field
- Jump between tracks while keeping the same caret position (nth character)
- Jump between mediums
- Select all text in track number and track length fields

**Comment by derat** [comment]
Makes sense! Just posting the comment I was writing in case it helps in the future:

---

I think `stopPropagation` only works if your listener and the server's listener are set on different elements, which is probably the case here -- If I'm remembering right, the server code installs a single listener on a parent element and uses Knockout to do routing to the inputs. Probably your listener is running first (if it's set on the input), and then `stopPropagation` prevents the event from bubbling out to the parent element.

`stopImmediatePropagation` keeps any other listeners from running, even if they're on the same element, but event listeners on a single element run in the order that they're registered, and I suspect that the server's listener gets registered before your script's listener, so this probably wouldn't make much of a difference.

Stopping propagation might break things if the server has other event listeners that should run, but I'm not sure if there's much that can be done about that. If you're okay with the server's up/down logic, I was thinking you could maybe change your listener to just call something like `setTimeout(() => input.setSelection(0, input.value.length), 0)` to select all the text after all the other listeners have run. Not sure if it'd work, though.

**Comment by jesus2099** [comment]
Thanks, I had approximately the same thoughts in mind. 😁

Especially this: 

> I think stopPropagation only works if your listener and the server's listener are set on different elements, which is probably the case here
