### ISSUE TITLE
"You should now disable STATIC_MENU" how?

### ISSUE THREAD

**Issue by karpuzikov** [jesus2099/konami-command#846]
how do i do that?
![image](https://github.com/user-attachments/assets/ba0d85f2-4ef3-4484-8c50-e4b755660a0f)

**Comment by jesus2099** [comment]
I added an explanation.

It's a must-know for this userscript, I should probably try to improve its visibility... 🤔

**Comment by karpuzikov** [comment]
it says now "you can find this in “Editing ▾” menu"
i mean... i just have no idea where to search for it

**Comment by jesus2099** [comment]
From any MusicBrainz page, click on the Editing menu, then on SUPER TURBO.
From there you can enable and disable any SUPER TURBO feature.

![image](https://github.com/user-attachments/assets/c3738f21-be0c-4b92-a183-7c7f3cf85d26)

**Comment by karpuzikov** [comment]
ohhh thanks)
