### ISSUE TITLE
Suggestion to add setting in `mb. INLINE STUFF` to fetch AcousticIDs or not

### ISSUE THREAD

**Issue by jerry-sileon** [jesus2099/konami-command#847]
I never use the AcousticIDs. Fetching them is a minor thing, but showing them can take a lot of space on some popular releases. I added a user style that hides `.ars` but it would be nice if it could be a setting.

**Comment by jesus2099** [comment]
You should already be able to hide them by clicking **hide** in the sidebar.
Same with ISRC.
