### ISSUE TITLE
USO to USMO: Match pattern enhancement

### ISSUE THREAD

**Issue by Martii** [jesus2099/konami-command#85]
May want to isolate `https?` and `\/\/` in case someone was using `//userscripts.org/...`

TIA

**Comment by jesus2099** [comment]
Thank you, Martii !
I have made a test suite on script’s homepage ([OUJS](https://openuserjs.org/scripts/jesus2099/USO_to_USMO)/[GF](https://greasyfork.org/scripts/11324-uso-to-usmo)).
If you have time, tell me if something else is missing… :)
I will fix the `//`, good catch !
