### ISSUE TITLE
Artist names with a leading dash return no DDG results

### ISSUE THREAD

**Issue by metaisfacil** [jesus2099/konami-command#852]
Title says it all. When an artist name leads with a dash, like [-tarrot-](https://beta.musicbrainz.org/artist/1cd3df2d-a883-4111-bcd6-6e9526dc1631) for instance, links that rely on DuckDuckGo to show links do not show any relevant results (of course, because a leading dash also happens to be an operator for excluding terms from searches).

**Comment by jesus2099** [comment]
https://musicbrainz.org/search?query=artistaccent%3A-&type=artist&limit=100&method=advanced

Unfortunately the `^` in `/^-/` is not taken in account but MB Lucene search.

**Comment by jesus2099** [comment]
I recently removed the quotes surrounding entity names for those basic searches, let's see why...

Because that would be the request fix.

**Comment by jesus2099** [comment]
I have restored the quotes, it was a regression.
Thank you @metaisfacil.
