### ISSUE TITLE
Window title with result count doesn't account for decimal separator

### ISSUE THREAD

**Issue by nimuxoha** [jesus2099/konami-command#854]
Once the edit results count reaches thousands only the first digit is display in the window title. 

For example:
https://musicbrainz.org/edit/open?page=11 should have "Found at least 1,000 edits" on the page (unless you are an extreme voter and almost finished) and the title should be changed to `[1000] Open edits - MusicBrainz` but it's actually changed to `[1] Open edits - MusicBrainz`

**Comment by jesus2099** [comment]
It's fixed now.
Thanks, @nimuxoha!
