### ISSUE TITLE
Link to other main chat channels

### ISSUE THREAD

**Issue by nimuxoha** [jesus2099/konami-command#880]
It would be nice if the `CHATLOGS-POWER-UP` script had support for other [main channels](https://chatlogs.metabrainz.org/) such as #bookbrainz and #listenbrainz. Right now, if you view those there is only a link to #musicbrainz:
![image](https://github.com/user-attachments/assets/588cf5bf-f359-4074-aa04-07e9a045784f)

**Comment by jesus2099** [comment]
For info, I dropped `#musicbrainz-ja` in 2021: https://github.com/jesus2099/konami-command/commit/1fff3ad269d0a18be8db6d9de0a60f3cbc78adfb ;)

**Comment by jesus2099** [comment]
There, I have added the main channels!
The others are quite empty.
