### ISSUE TITLE
PetitLyrics: Non-lyrics URL is redirected to undefined ID

### ISSUE THREAD

**Issue by Uranite** [jesus2099/konami-command#882]
Hi, there’s an issue when we try to open an artist link on PetitLyrics. For example, if we open https://petitlyrics.com/lyrics/artist/220763 with the script enabled, it redirects to https://petitlyrics.com/lyrics/undefined.
We can resolve this by adding `// @exclude      *://petitlyrics.com/lyrics/artist/*` to exclude artist links so that this issue doesn't happen.

**Comment by jesus2099** [comment]
Thank you, @Uranite!
It should be fixed, now.
