### ISSUE TITLE
github INSTALL USER SCRIPT: Upward migration issue

### ISSUE THREAD

**Issue by Martii** [jesus2099/konami-command#93]
Noticed today that this script went away and morphed into [INSTALL-USER-SCRIPT.user.js](https://github.com/jesus2099/konami-command/blob/master/INSTALL-USER-SCRIPT.user.js)

First off **BOO!**  \*/end playful heckling\* ;)

Might be prudent to offer a migration update path perhaps through script updates... kewl script btw... I'll go revote on it on OUJS but I really don't use the other include'd sites but I guess that's not a huge deal... the "BOO" part is because I have no idea when you did this change or if you just git renamed the file or what.

Just thought I'd offer some constructive advice. :)

Until next time.

**Comment by jesus2099** [comment]
Well as I first added bitbucket support then gitlab to this once github only script… I felt it was not good to keep the github name only…

I made some tests with a fake script (c9b17e36eeaab030e54afbb39e6e7cab5e860ae8) to how could a rename be done and people don’t miss updates.

I first change the update URL to target name, wait for days or, better, weeks, then rename the script…

This was OK for Greasemonkey, Violentmonkey and Tampermonkey.

For this script I changed as follow :
* 3610c9ef111f3e93e7539efc4b3999662f0e95f2 (2015-04-10) update URL → bitbucket-github
* 2345c3015812a2b7068450cce874a74f109c5789 (2015-04-18) rename script → bitbucket-github (only 8 days but the script was not yet used apart by me, I guess)
* 95ef59c898e308543513728978a9924cdd680b1c (2015-04-18) update URL → INSTALL
* a24471e3220a95c9ac6dbab64a0b44b7fc34255e (2015-07-09) rename script → INSTALL

You say I could place some empty scripts in the old names, with update/download URL pointing to new one, in case someone has the old names ? Maybe yes… I have some other renamed script I could do same… but that makes some bogus scripts in the repository…

Source : 
https://github.com/jesus2099/konami-command/commits/master/github_INSTALL-USER-SCRIPT.user.js
https://github.com/jesus2099/konami-command/commits/master/bitbucket-github_INSTALL-USER-SCRIPT.user.js
https://github.com/jesus2099/konami-command/commits/master/INSTALL-USER-SCRIPT.user.js

**Comment by Martii** [comment]
Usually if I end-of-life a script I'll usually take out all the code and do an alert to nag those that don't update constantly... if I were to do that here on GH I'd probably move it to a folder of `eol`'s... that way they are still findable with searching... as per the `@downloadURL` you could redirect to the new one although that might raise an eyebrow or two.... given enough time it might not. My laptop for example hasn't been turned on in several weeks and if someone eol'd a script I would be sol'd ;).

Thanks for the commit history links... shows me how long I've been without the updated version LOL.

**Comment by jesus2099** [comment]
Keeping a blank version of past scripts is a good idea… although it is some cluttering in the folder list…
I don’t know… I hope I will not make too much renames in the future. :)
