### ISSUE TITLE
MASS MERGE: Match artists too for unordered

### ISSUE THREAD

**Issue by pankkake** [jesus2099/konami-command#98]
When matching unordered tracks, the wrong ones can be matches for releases where the title is the same, and the artist is not.

It's very rarely an issue, since I can manually check and not merge, however there is one case where it sucks: tribute albums. Those often have the same title more than once in the release, and the wrong ones are automatically matched, so you still have to manually merge in the end.

Testing:
https://musicbrainz.org/release/531e9224-04a3-4df6-b8d5-4f80dac7cbf1
https://musicbrainz.org/release/512188d3-8408-34fd-a478-3c823e61ca8a (and other volumes of Blackest Album)

**Comment by jesus2099** [comment]
On the other hand, it would be troublesome to always only align tracks with same artist credit.
Maybe a new <kbd>Match unordered track titles and AC</kbd> button should be inserted between existing <kbd>Match unordered track titles</kbd> and <kbd>Sequential</kbd> buttons… ?

The user interface is already becoming quite complex IMO… :/ no ?

**Comment by pankkake** [comment]
I agree and I have no solution!

**Comment by jesus2099** [comment]
A quick fix is to always check artists for the existing button.
I made it but I think we should have choice and make it another button…
But if you want to try, replace function `bestStartPosition()` (line `560`) with : 

    	function bestStartPosition(pLoc) {
    		for (var loc = (typeof pLoc != "undefined" ? pLoc : 0); loc < (typeof pLoc != "undefined" ? pLoc + 1 : localRelease.tracks.length); loc++) for (var rem = 0; rem < remoteRelease.tracks.length; rem++) if (almostSame(localRelease.tracks[loc].name, remoteRelease.tracks[rem].name) && almostSame(html2text(localRelease.tracks[loc].artistCredit), html2text(remoteRelease.tracks[rem].artistCredit))) {
    			return loc - rem;
    		}
    		return null;
    	}

See what it does when it’s always. Tell me. :)

**Comment by pankkake** [comment]
Great, thanks :)
